-- Curated first Kenya catalog batch. Product families appear once; verified
-- sellable formats live in catalog_product_variants. No shop price is seeded.
-- The upserts make this migration safe to rerun.

with families(slug, name, brand, category, keywords) as (values
  ('tusker-lager','Tusker Lager','Tusker','beer',array['tusker','lager','kbl']),
  ('tusker-lite','Tusker Lite','Tusker','beer',array['tusker','light','kbl']),
  ('tusker-malt','Tusker Malt','Tusker','beer',array['tusker','malt','kbl']),
  ('tusker-cider','Tusker Cider','Tusker','cider',array['tusker','cider','kbl']),
  ('tusker-ndimu','Tusker Ndimu','Tusker','beer',array['tusker','lemon','ndimu']),
  ('white-cap-lager','White Cap Lager','White Cap','beer',array['whitecap','lager']),
  ('white-cap-crisp','White Cap Crisp','White Cap','beer',array['whitecap','crisp']),
  ('pilsner-lager','Pilsner Lager','Pilsner','beer',array['pilsner','lager']),
  ('guinness-foreign-extra-stout','Guinness Foreign Extra Stout','Guinness','beer',array['guiness','stout']),
  ('heineken-original','Heineken Original','Heineken','beer',array['heineken','lager']),
  ('desperados-original','Desperados Original','Desperados','beer',array['desperados','tequila beer']),
  ('bavaria-original','Bavaria Original','Bavaria','beer',array['bavaria','lager']),
  ('corona-extra','Corona Extra','Corona','beer',array['corona','lager']),
  ('savanna-dry','Savanna Dry','Savanna','cider',array['savanna','cider']),
  ('hunters-dry','Hunters Dry','Hunter''s','cider',array['hunters','cider']),
  ('snapp','Snapp','Snapp','cider',array['snapp','apple']),
  ('kenyan-originals-craft-cider','Kenyan Originals Craft Cider','Kenyan Originals','cider',array['ko','kenyan originals','cider']),
  ('gilbeys-premium-dry-gin','Gilbey''s Premium Dry Gin','Gilbey''s','gin',array['gilbeys','dry gin']),
  ('gordons-london-dry-gin','Gordon''s London Dry Gin','Gordon''s','gin',array['gordons','dry gin']),
  ('bombay-sapphire','Bombay Sapphire','Bombay Sapphire','gin',array['bombay','sapphire','gin']),
  ('beefeater-london-dry-gin','Beefeater London Dry Gin','Beefeater','gin',array['beefeater','gin']),
  ('hendricks-gin','Hendrick''s Gin','Hendrick''s','gin',array['hendricks','gin']),
  ('tanqueray-no-ten','Tanqueray No. Ten','Tanqueray','gin',array['tanqueray','no 10','gin']),
  ('seagrams-extra-dry-gin','Seagram''s Extra Dry Gin','Seagram''s','gin',array['seagrams','gin']),
  ('new-amsterdam-gin','New Amsterdam Gin','New Amsterdam','gin',array['new amsterdam','gin']),
  ('bulldog-london-dry-gin','Bulldog London Dry Gin','Bulldog','gin',array['bulldog','gin']),
  ('chrome-gin','Chrome Gin','Chrome','gin',array['chrome','gin']),
  ('58-classic-premium-gin','58 Classic Premium Gin','58 Gin','gin',array['58','classic','gin']),
  ('absolut-original-vodka','Absolut Original Vodka','Absolut','vodka',array['absolut','vodka']),
  ('absolut-vanilia','Absolut Vanilia','Absolut','vodka',array['absolut','vanilla','vodka']),
  ('absolut-elyx','Absolut Elyx','Absolut','vodka',array['absolut','elyx','vodka']),
  ('smirnoff-red-label-vodka','Smirnoff Red Label Vodka','Smirnoff','vodka',array['smirnoff','red','vodka']),
  ('smirnoff-vanilla','Smirnoff Vanilla','Smirnoff','vodka',array['smirnoff','vanilla']),
  ('smirnoff-orange','Smirnoff Orange','Smirnoff','vodka',array['smirnoff','orange']),
  ('flirt-green-apple-vodka','Flirt Green Apple Vodka','Flirt','vodka',array['flirt','green apple']),
  ('flirt-red-vodka','Flirt Red Vodka','Flirt','vodka',array['flirt','red']),
  ('class-21-vodka','Class 21 Vodka','Class 21','vodka',array['class 21','vodka']),
  ('ciroc-ultra-premium-vodka','Cîroc Ultra-Premium Vodka','Cîroc','vodka',array['ciroc','vodka']),
  ('grey-goose-vodka','Grey Goose Vodka','Grey Goose','vodka',array['grey goose','vodka']),
  ('hennessy-vs','Hennessy VS','Hennessy','cognac',array['hennessy','vs','cognac']),
  ('hennessy-vsop','Hennessy VSOP','Hennessy','cognac',array['hennessy','vsop','cognac']),
  ('hennessy-xo','Hennessy XO','Hennessy','cognac',array['hennessy','xo','cognac']),
  ('martell-vs','Martell VS','Martell','cognac',array['martel','martell','vs']),
  ('martell-vsop','Martell VSOP','Martell','cognac',array['martel','martell','vsop']),
  ('martell-cordon-bleu','Martell Cordon Bleu','Martell','cognac',array['martel','martell','cordon bleu']),
  ('martell-xo','Martell XO','Martell','cognac',array['martel','martell','xo']),
  ('courvoisier-vs','Courvoisier VS','Courvoisier','cognac',array['courvoisier','vs']),
  ('courvoisier-vsop','Courvoisier VSOP','Courvoisier','cognac',array['courvoisier','vsop']),
  ('courvoisier-xo','Courvoisier XO','Courvoisier','cognac',array['courvoisier','xo']),
  ('remy-martin-vsop','Rémy Martin VSOP','Rémy Martin','cognac',array['remy','vsop','cognac']),
  ('johnnie-walker-red-label','Johnnie Walker Red Label','Johnnie Walker','whisky',array['johnny walker','red label']),
  ('johnnie-walker-black-label','Johnnie Walker Black Label','Johnnie Walker','whisky',array['johnny walker','black label']),
  ('johnnie-walker-double-black','Johnnie Walker Double Black','Johnnie Walker','whisky',array['johnny walker','double black']),
  ('johnnie-walker-gold-label-reserve','Johnnie Walker Gold Label Reserve','Johnnie Walker','whisky',array['johnny walker','gold label']),
  ('johnnie-walker-blue-label','Johnnie Walker Blue Label','Johnnie Walker','whisky',array['johnny walker','blue label']),
  ('jameson-irish-whiskey','Jameson Irish Whiskey','Jameson','whisky',array['jameson','irish whiskey']),
  ('jack-daniels-old-no-7','Jack Daniel''s Old No. 7','Jack Daniel''s','whisky',array['jack daniels','tennessee']),
  ('william-lawsons-blended-scotch','William Lawson''s Blended Scotch','William Lawson''s','whisky',array['william lawson','scotch']),
  ('glenfiddich-12-year-old','Glenfiddich 12 Year Old','Glenfiddich','whisky',array['glenfiddich','12 years']),
  ('glenfiddich-18-year-old','Glenfiddich 18 Year Old','Glenfiddich','whisky',array['glenfiddich','18 years']),
  ('glenfiddich-21-year-old','Glenfiddich 21 Year Old','Glenfiddich','whisky',array['glenfiddich','21 years']),
  ('glenmorangie-the-original','Glenmorangie The Original','Glenmorangie','whisky',array['glenmorangie','original']),
  ('glenmorangie-lasanta','Glenmorangie Lasanta','Glenmorangie','whisky',array['glenmorangie','lasanta']),
  ('glenmorangie-quinta-ruban','Glenmorangie Quinta Ruban','Glenmorangie','whisky',array['glenmorangie','quinta ruban']),
  ('glenmorangie-18-year-old','Glenmorangie 18 Year Old','Glenmorangie','whisky',array['glenmorangie','18 years']),
  ('chivas-regal-12','Chivas Regal 12','Chivas Regal','whisky',array['chivas','12 years']),
  ('the-famous-grouse','The Famous Grouse','The Famous Grouse','whisky',array['famous grouse','scotch']),
  ('black-and-white-whisky','Black & White Whisky','Black & White','whisky',array['black white','scotch']),
  ('ballantines-finest','Ballantine''s Finest','Ballantine''s','whisky',array['ballantines','scotch']),
  ('grants-triple-wood','Grant''s Triple Wood','Grant''s','whisky',array['grants','scotch']),
  ('all-seasons-premium-whisky','All Seasons Premium Whisky','All Seasons','whisky',array['all seasons','whiskey']),
  ('8pm-indian-whisky','8PM Indian Whisky','8PM','whisky',array['8 pm','indian whiskey']),
  ('whytehall-honey-whiskey','Whytehall Honey Whiskey','Whytehall','whisky',array['whytehall','honey']),
  ('captain-morgan-original-spiced-gold','Captain Morgan Original Spiced Gold','Captain Morgan','rum',array['captain morgan','spiced rum']),
  ('captain-morgan-black-spiced','Captain Morgan Black Spiced','Captain Morgan','rum',array['captain morgan','black rum']),
  ('bacardi-carta-blanca','Bacardi Carta Blanca','Bacardi','rum',array['bacardi','superior','white rum']),
  ('bacardi-carta-oro','Bacardi Carta Oro','Bacardi','rum',array['bacardi','gold rum']),
  ('bacardi-carta-negra','Bacardi Carta Negra','Bacardi','rum',array['bacardi','black rum']),
  ('malibu-original','Malibu Original','Malibu','rum',array['malibu','coconut rum']),
  ('old-monk-the-legend','Old Monk The Legend','Old Monk','rum',array['old monk','dark rum']),
  ('myerss-original-dark','Myers''s Original Dark','Myers''s','rum',array['myers','dark rum']),
  ('lambs-navy-rum','Lamb''s Navy Rum','Lamb''s','rum',array['lambs','navy rum']),
  ('afri-bull-cafe-rum','Afri Bull Café Rum','Afri Bull','rum',array['afri bull','coffee rum']),
  ('jose-cuervo-especial-gold','Jose Cuervo Especial Gold','Jose Cuervo','tequila',array['cuervo','gold tequila']),
  ('jose-cuervo-especial-silver','Jose Cuervo Especial Silver','Jose Cuervo','tequila',array['cuervo','silver tequila']),
  ('olmeca-gold','Olmeca Gold','Olmeca','tequila',array['olmeca','gold tequila']),
  ('olmeca-blanco','Olmeca Blanco','Olmeca','tequila',array['olmeca','silver tequila']),
  ('sierra-gold','Sierra Gold','Sierra','tequila',array['sierra','gold tequila']),
  ('sierra-silver','Sierra Silver','Sierra','tequila',array['sierra','silver tequila']),
  ('camino-real-gold','Camino Real Gold','Camino Real','tequila',array['camino','gold tequila']),
  ('camino-real-blanco','Camino Real Blanco','Camino Real','tequila',array['camino','clear tequila']),
  ('patron-silver','Patrón Silver','Patrón','tequila',array['patron','silver tequila']),
  ('don-julio-anejo','Don Julio Añejo','Don Julio','tequila',array['don julio','anejo tequila']),
  ('amarula-cream','Amarula Cream','Amarula','liqueur',array['amarula','cream liqueur']),
  ('baileys-original-irish-cream','Baileys Original Irish Cream','Baileys','liqueur',array['baileys','irish cream']),
  ('kahlua-coffee-liqueur','Kahlúa Coffee Liqueur','Kahlúa','liqueur',array['kahlua','coffee liqueur']),
  ('tia-maria-coffee-liqueur','Tia Maria Coffee Liqueur','Tia Maria','liqueur',array['tia maria','coffee liqueur']),
  ('southern-comfort-original','Southern Comfort Original','Southern Comfort','liqueur',array['southern comfort','liqueur']),
  ('sheridans-coffee-layered-liqueur','Sheridan''s Coffee Layered Liqueur','Sheridan''s','liqueur',array['sheridans','coffee cream']),
  ('tequila-rose-strawberry-cream','Tequila Rose Strawberry Cream','Tequila Rose','liqueur',array['tequila rose','strawberry cream']),
  ('4th-street-sweet-rose','4th Street Sweet Rosé','4th Street','wine',array['fourth street','rose wine']),
  ('4th-street-sweet-red','4th Street Sweet Red','4th Street','wine',array['fourth street','red wine']),
  ('4th-street-sweet-white','4th Street Sweet White','4th Street','wine',array['fourth street','white wine']),
  ('belaire-brut','Luc Belaire Brut Gold','Luc Belaire','wine',array['belaire','brut','sparkling']),
  ('belaire-rare-rose','Luc Belaire Rare Rosé','Luc Belaire','wine',array['belaire','rose','sparkling']),
  ('four-cousins-sweet-red','Four Cousins Sweet Red','Four Cousins','wine',array['four cousins','red wine']),
  ('four-cousins-sweet-white','Four Cousins Sweet White','Four Cousins','wine',array['four cousins','white wine']),
  ('drostdy-hof-claret-select','Drostdy-Hof Claret Select','Drostdy-Hof','wine',array['drostdy hof','red wine']),
  ('nederburg-barone','Nederburg Baronne','Nederburg','wine',array['nederburg','baronne','red wine']),
  ('namaqua-sweet-red','Namaqua Sweet Red','Namaqua','wine',array['namaqua','red wine']),
  ('coca-cola-original','Coca-Cola Original','Coca-Cola','soft-drink',array['coke','soda','mixer']),
  ('coca-cola-light','Coca-Cola Light','Coca-Cola','soft-drink',array['coke light','diet coke']),
  ('fanta-orange','Fanta Orange','Fanta','soft-drink',array['fanta','orange soda']),
  ('fanta-pineapple','Fanta Pineapple','Fanta','soft-drink',array['fanta','pineapple soda']),
  ('sprite','Sprite','Sprite','soft-drink',array['sprite','lemon soda']),
  ('schweppes-tonic-water','Schweppes Tonic Water','Schweppes','mixer',array['schweppes','tonic','mixer']),
  ('red-bull-energy-drink','Red Bull Energy Drink','Red Bull','energy-drink',array['redbull','energy']),
  ('monster-energy-original','Monster Energy Original','Monster','energy-drink',array['monster','energy']),
  ('krest-bitter-lemon','Krest Bitter Lemon','Krest','mixer',array['krest','bitter lemon','mixer']),
  ('stoney-tangawizi','Stoney Tangawizi','Stoney','soft-drink',array['stoney','ginger soda']),
  ('william-lawsons-super-spiced','William Lawson''s Super Spiced','William Lawson''s','whisky',array['william lawson','spiced whisky']),
  ('zafiro-pink-premium-gin','Zafiro Pink Premium Gin','Zafiro','gin',array['zafiro','pink gin']),
  ('white-owl-whisky','White Owl Whisky','White Owl','whisky',array['white owl','whiskey']),
  ('whitelace-gin','Whitelace Gin','Whitelace','gin',array['whitelace','gin']),
  ('johnnie-walker-white-walker','Johnnie Walker White Walker','Johnnie Walker','whisky',array['white walker','johnny walker']),
  ('viceroy-5-year-old-brandy','Viceroy 5 Year Old Brandy','Viceroy','brandy',array['viceroy','5 years','brandy']),
  ('viceroy-10-year-old-brandy','Viceroy 10 Year Old Brandy','Viceroy','brandy',array['viceroy','10 years','brandy']),
  ('waterproof-blended-malt','Waterproof Blended Malt','Waterproof','whisky',array['waterproof','malt scotch']),
  ('vat-69-blended-scotch','Vat 69 Blended Scotch','Vat 69','whisky',array['vat69','scotch']),
  ('va-imperial-cream','V&A Imperial Cream','V&A','liqueur',array['v and a','imperial cream']),
  ('two-keys-whisky','Two Keys Whisky','Two Keys','whisky',array['two keys','whiskey']),
  ('tullamore-dew','Tullamore D.E.W.','Tullamore D.E.W.','whisky',array['tullamore dew','irish whiskey']),
  ('triple-ace-vodka','Triple Ace Vodka','Triple Ace','vodka',array['triple ace','vodka']),
  ('ti-white-house-premium-whisky','TI White House Premium Whisky','TI White House','whisky',array['white house','whiskey']),
  ('three-barrels-vsop','Three Barrels VSOP','Three Barrels','brandy',array['three barrels','vsop','brandy']),
  ('famous-grouse-sherry-cask','The Famous Grouse Sherry Cask Finish','The Famous Grouse','whisky',array['famous grouse','sherry cask']),
  ('singleton-dufftown-12','The Singleton Dufftown 12 Year Old','The Singleton','whisky',array['singleton','dufftown','12 years']),
  ('macallan-double-cask-15','The Macallan Double Cask 15 Year Old','The Macallan','whisky',array['macallan','double cask','15 years']),
  ('glenlivet-founders-reserve','The Glenlivet Founder''s Reserve','The Glenlivet','whisky',array['glenlivet','founders reserve']),
  ('glenlivet-caribbean-reserve','The Glenlivet Caribbean Reserve','The Glenlivet','whisky',array['glenlivet','caribbean reserve']),
  ('glenlivet-12','The Glenlivet 12 Year Old','The Glenlivet','whisky',array['glenlivet','12 years']),
  ('glenlivet-15','The Glenlivet 15 Year Old','The Glenlivet','whisky',array['glenlivet','15 years']),
  ('glenlivet-18','The Glenlivet 18 Year Old','The Glenlivet','whisky',array['glenlivet','18 years']),
  ('glen-silver-single-malt','The Glen Silver Single Malt','The Glen Silver','whisky',array['glen silver','single malt']),
  ('glen-silver-12','The Glen Silver 12 Year Old','The Glen Silver','whisky',array['glen silver','12 years']),
  ('tanqueray-rangpur','Tanqueray Rangpur','Tanqueray','gin',array['tanqueray','rangpur','lime gin']),
  ('tanqueray-london-dry','Tanqueray London Dry Gin','Tanqueray','gin',array['tanqueray','london dry']),
  ('tanqueray-blackcurrant-royale','Tanqueray Blackcurrant Royale','Tanqueray','gin',array['tanqueray','blackcurrant','royale']),
  ('teachers-highland-cream','Teacher''s Highland Cream','Teacher''s','whisky',array['teachers','highland cream']),
  ('teremana-tequila','Teremana Tequila','Teremana','tequila',array['teremana','tequila']),
  ('st-remy-vsop','St-Rémy VSOP','St-Rémy','brandy',array['st remy','vsop','brandy']),
  ('st-remy-xo','St-Rémy XO','St-Rémy','brandy',array['st remy','xo','brandy']),
  ('strawberry-lips','Strawberry Lips','Strawberry Lips','liqueur',array['strawberry lips','tequila liqueur']),
  ('strettons-original-dry-gin','Stretton''s Original London Dry Gin','Stretton''s','gin',array['strettons','dry gin']),
  ('strettons-triple-berry','Stretton''s Triple Berry Gin','Stretton''s','gin',array['strettons','triple berry']),
  ('strettons-wild-berries','Stretton''s Wild Berries Gin','Stretton''s','gin',array['strettons','wild berries']),
  ('smirnoff-black-ice','Smirnoff Black Ice','Smirnoff','ready-to-drink',array['smirnoff','black ice','rtd']),
  ('smirnoff-blue-vodka','Smirnoff Blue Vodka','Smirnoff','vodka',array['smirnoff','blue vodka']),
  ('smirnoff-ice-pineapple-punch','Smirnoff Ice Pineapple Punch','Smirnoff','ready-to-drink',array['smirnoff','pineapple','rtd']),
  ('scots-gold-black','Scots Gold Black','Scots Gold','whisky',array['scots gold','black']),
  ('scots-gold-8','Scots Gold 8 Year Old','Scots Gold','whisky',array['scots gold','8 years']),
  ('scots-gold-12','Scots Gold 12 Year Old','Scots Gold','whisky',array['scots gold','12 years']),
  ('scots-gold-red','Scots Gold Red','Scots Gold','whisky',array['scots gold','red']),
  ('shustoff-old-history','Shustoff Old History','Shustoff','cognac',array['shustoff','old history']),
  ('silver-anchor-dry-gin','Silver Anchor Premium London Dry Gin','Silver Anchor','gin',array['silver anchor','dry gin']),
  ('singleton-15','The Singleton 15 Year Old','The Singleton','whisky',array['singleton','15 years']),
  ('singleton-18','The Singleton 18 Year Old','The Singleton','whisky',array['singleton','18 years']),
  ('sir-edwards-blended-scotch','Sir Edward''s Blended Scotch','Sir Edward''s','whisky',array['sir edwards','scotch']),
  ('six-dogs-blue-gin','Six Dogs Blue Gin','Six Dogs','gin',array['six dogs','blue gin']),
  ('royal-stag-superior','Royal Stag Superior','Royal Stag','whisky',array['royal stag','whiskey']),
  ('rose-dargent-pink-strawberry','Rose D''Argent Pink Strawberry Gin','D''Argent','gin',array['rose d argent','pink','strawberry gin']),
  ('1659-classic-red','1659 Classic Red','1659 Wines','wine',array['1659','red wine']),
  ('7-hills-natural-sweet-white','7 Hills Natural Sweet White','7 Hills Wines','wine',array['7 hills','sweet white']),
  ('zapallares-sauvignon-blanc','Zapallares Sauvignon Blanc','Zapallares','wine',array['zapallares','sauvignon blanc']),
  ('welmoed-shiraz','Welmoed Shiraz','Welmoed','wine',array['welmoed','shiraz']),
  ('welmoed-pinotage','Welmoed Pinotage','Welmoed','wine',array['welmoed','pinotage']),
  ('welmoed-rose','Welmoed Rosé','Welmoed','wine',array['welmoed','rose']),
  ('welmoed-pinot-grigio','Welmoed Pinot Grigio','Welmoed','wine',array['welmoed','pinot grigio']),
  ('welmoed-chenin-blanc','Welmoed Chenin Blanc','Welmoed','wine',array['welmoed','chenin blanc']),
  ('welmoed-chardonnay','Welmoed Chardonnay','Welmoed','wine',array['welmoed','chardonnay']),
  ('welmoed-merlot','Welmoed Merlot','Welmoed','wine',array['welmoed','merlot']),
  ('veuve-du-vernay-brut-rose','Veuve du Vernay Brut Rosé','Veuve du Vernay','wine',array['veuve du vernay','brut rose']),
  ('veuve-du-vernay-ice','Veuve du Vernay Ice','Veuve du Vernay','wine',array['veuve du vernay','ice']),
  ('veuve-du-vernay-brut','Veuve du Vernay Brut','Veuve du Vernay','wine',array['veuve du vernay','brut']),
  ('veuve-ambal-brut','Veuve Ambal Brut','Veuve Ambal','wine',array['veuve ambal','brut']),
  ('veuve-ambal-rose-brut','Veuve Ambal Rosé Brut','Veuve Ambal','wine',array['veuve ambal','rose brut']),
  ('tilia-malbec','Tilia Malbec','Tilia','wine',array['tilia','malbec']),
  ('tocornal-merlot','Tocornal Merlot','Tocornal','wine',array['tocornal','merlot']),
  ('tocornal-chardonnay','Tocornal Chardonnay','Tocornal','wine',array['tocornal','chardonnay']),
  ('tocornal-sauvignon-blanc','Tocornal Sauvignon Blanc','Tocornal','wine',array['tocornal','sauvignon blanc']),
  ('the-guvnor-red','The Guv''nor Red','The Guv''nor','wine',array['guvnor','red wine']),
  ('the-guvnor-white','The Guv''nor White','The Guv''nor','wine',array['guvnor','white wine']),
  ('taittinger-prestige-rose','Taittinger Prestige Rosé','Taittinger','wine',array['taittinger','prestige rose','champagne']),
  ('taittinger-brut-reserve','Taittinger Brut Réserve','Taittinger','wine',array['taittinger','reserve','champagne']),
  ('soupcon-rose-danjou','Soupçon de Fruit Rosé d''Anjou','Soupçon','wine',array['soupcon','rose anjou']),
  ('soupcon-rose-de-loire','Soupçon de Fruit Rosé de Loire','Soupçon','wine',array['soupcon','rose loire']),
  ('signore-giuseppe-prosecco','Signore Giuseppe Prosecco','Signore Giuseppe','wine',array['signore giuseppe','prosecco']),
  ('signore-giuseppe-prosecco-rose','Signore Giuseppe Prosecco Rosé','Signore Giuseppe','wine',array['signore giuseppe','prosecco rose']),
  ('samatha-sweet-white','Samatha Sweet White','Samatha','wine',array['samatha','sweet white']),
  ('samatha-rose','Samatha Rosé','Samatha','wine',array['samatha','rose']),
  ('rooiberg-natural-sweet-rose','Rooiberg Natural Sweet Rosé','Rooiberg','wine',array['rooiberg','sweet rose']),
  ('rooiberg-natural-sweet-red','Rooiberg Natural Sweet Red','Rooiberg','wine',array['rooiberg','sweet red']),
  ('rooiberg-colombar','Rooiberg Colombar','Rooiberg','wine',array['rooiberg','colombar']),
  ('rosso-nobile-espresso','Rosso Nobile Espresso','Rosso Nobile','wine',array['rosso nobile','espresso']),
  ('rosso-nobile-cherry','Rosso Nobile Cherry','Rosso Nobile','wine',array['rosso nobile','cherry']),
  ('rosso-nobile-chocolate','Rosso Nobile Chocolate','Rosso Nobile','wine',array['rosso nobile','chocolate']),
  ('rosso-nobile-nougat','Rosso Nobile Nougat','Rosso Nobile','wine',array['rosso nobile','nougat']),
  ('rosso-nobile-raspberry-lemon','Rosso Nobile Raspberry & Lemon','Rosso Nobile','wine',array['rosso nobile','raspberry lemon']),
  ('rosso-bianco-vaniglia','Rosso Bianco Nobile Alla Vaniglia','Rosso Nobile','wine',array['rosso bianco','vaniglia','vanilla']),
  ('rust-en-vrede-syrah','Rust en Vrede Stellenbosch Syrah','Rust en Vrede','wine',array['rust en vrede','syrah']),
  ('rendez-vous-sparkling-white-grape','Rendez Vous Sparkling White Grape','Rendez Vous','wine',array['rendez vous','non alcoholic','white grape']),
  ('rendez-vous-sparkling-apple','Rendez Vous Sparkling Apple','Rendez Vous','wine',array['rendez vous','non alcoholic','apple']),
  ('rendez-vous-sparkling-blue','Rendez Vous Sparkling Blue','Rendez Vous','wine',array['rendez vous','non alcoholic','blue']),
  ('robertson-sweet-white','Robertson Winery Sweet White','Robertson Winery','wine',array['robertson','sweet white']),
  ('robertson-sweet-red-sparkling','Robertson Winery Sweet Red Sparkling','Robertson Winery','wine',array['robertson','sweet red','sparkling']),
  ('robertson-red','Robertson Winery Red','Robertson Winery','wine',array['robertson','red wine']),
  ('robertson-sweet-rose','Robertson Winery Sweet Rosé','Robertson Winery','wine',array['robertson','sweet rose']),
  ('pierre-marcel-sweet-rose','Pierre Marcel Sweet Rosé','Pierre Marcel','wine',array['pierre marcel','sweet rose']),
  ('pierre-marcel-sweet-red','Pierre Marcel Sweet Red','Pierre Marcel','wine',array['pierre marcel','sweet red']),
  ('pierre-marcel-sweet-white','Pierre Marcel Sweet White','Pierre Marcel','wine',array['pierre marcel','sweet white']),
  ('poeti-prosecco-doc-rose','Poeti Prosecco DOC Rosé','Poeti','wine',array['poeti','prosecco','rose']),
  ('pierre-jourdan-belle-rose','Pierre Jourdan Belle Rosé','Pierre Jourdan','wine',array['pierre jourdan','belle rose']),
  ('pierre-jourdan-brut','Pierre Jourdan Cap Classique Brut','Pierre Jourdan','wine',array['pierre jourdan','brut','sparkling']),
  ('olepasu-white','Olepasu White','Olepasu','wine',array['olepasu','white wine']),
  ('olepasu-red-dry','Olepasu Red Dry','Olepasu','wine',array['olepasu','dry red']),
  ('nederburg-shiraz','Nederburg Shiraz','Nederburg','wine',array['nederburg','shiraz']),
  ('nederburg-pinotage','Nederburg Pinotage','Nederburg','wine',array['nederburg','pinotage']),
  ('nederburg-merlot','Nederburg Merlot','Nederburg','wine',array['nederburg','merlot']),
  ('nederburg-cabernet-sauvignon','Nederburg Cabernet Sauvignon','Nederburg','wine',array['nederburg','cabernet sauvignon']),
  ('nederburg-sauvignon-blanc','Nederburg Sauvignon Blanc','Nederburg','wine',array['nederburg','sauvignon blanc']),
  ('mulderbosch-sparkling-rose','Mulderbosch Sparkling Rosé','Mulderbosch','wine',array['mulderbosch','sparkling rose']),
  ('mulderbosch-chenin-blanc-sparkling','Mulderbosch Chenin Blanc Sparkling','Mulderbosch','wine',array['mulderbosch','chenin blanc','sparkling']),
  ('mulderbosch-cabernet-rose','Mulderbosch Cabernet Sauvignon Rosé','Mulderbosch','wine',array['mulderbosch','cabernet rose']),
  ('mucho-mas-red','Mucho Más Red','Mucho Más','wine',array['mucho mas','red wine']),
  ('mucho-mas-white','Mucho Más White','Mucho Más','wine',array['mucho mas','white wine']),
  ('moet-chandon-brut-imperial','Moët & Chandon Brut Impérial','Moët & Chandon','wine',array['moet','chandon','brut imperial','champagne']),
  ('moet-chandon-nectar-imperial','Moët & Chandon Nectar Impérial','Moët & Chandon','wine',array['moet','chandon','nectar imperial','champagne']),
  ('mohans-reserve-sweet-white','Mohan''s Reserve Natural Sweet White','Mohan''s','wine',array['mohans','sweet white']),
  ('martini-dolce-zero','Martini Dolce 0.0','Martini','wine',array['martini','non alcoholic','sparkling grape']),
  ('mikado-lychee','Mikado Lychee','Mikado','wine',array['mikado','lychee','sweet wine']),
  ('mikado-passion-fruit','Mikado Passion Fruit','Mikado','wine',array['mikado','passion fruit','sweet wine']),
  ('mikado-cherry','Mikado Cherry','Mikado','wine',array['mikado','cherry','red wine']),
  ('mikado-pineapple','Mikado Pineapple','Mikado','wine',array['mikado','pineapple','sweet wine']),
  ('mateus-original-rose','Mateus The Original Rosé','Mateus','wine',array['mateus','original rose']),
  ('chapoutier-belleruche-white','M. Chapoutier Belleruche White','M. Chapoutier','wine',array['chapoutier','belleruche','white wine']),
  ('chapoutier-la-ciboise-rouge','M. Chapoutier La Ciboise Rouge','M. Chapoutier','wine',array['chapoutier','la ciboise','red wine']),
  ('leopards-leap-cabernet-merlot','Leopard''s Leap Cabernet Sauvignon Merlot','Leopard''s Leap','wine',array['leopards leap','cabernet merlot']),
  ('leopards-leap-merlot','Leopard''s Leap Merlot','Leopard''s Leap','wine',array['leopards leap','merlot']),
  ('le-filou-sweet-rouge','Le Filou Sweet Rouge','Le Filou','wine',array['le filou','sweet red']),
  ('la-motte-pierneef-syrah-viognier','La Motte Pierneef Syrah Viognier','La Motte','wine',array['la motte','pierneef','syrah viognier'])
)
insert into public.catalog_products (slug, name, brand, category, keywords)
select slug, name, brand, category, keywords from families
on conflict (slug) do update set
  name = excluded.name,
  brand = excluded.brand,
  category = excluded.category,
  keywords = excluded.keywords,
  active = true,
  updated_at = now();

with variant_data(slug, volume_value, volume_unit, package_type) as (values
  ('tusker-lager',500,'ml','Bottle'),('tusker-lager',500,'ml','Can'),('tusker-lager',6,'piece','Six pack'),
  ('tusker-lite',500,'ml','Can'),('tusker-lite',6,'piece','Six pack'),
  ('tusker-malt',500,'ml','Bottle'),('tusker-malt',500,'ml','Can'),('tusker-malt',6,'piece','Six pack'),
  ('tusker-cider',500,'ml','Bottle'),('tusker-cider',6,'piece','Six pack'),('tusker-ndimu',300,'ml','Bottle'),
  ('white-cap-lager',500,'ml','Bottle'),('white-cap-lager',500,'ml','Can'),('white-cap-lager',6,'piece','Six pack'),
  ('white-cap-crisp',330,'ml','Bottle'),('pilsner-lager',500,'ml','Bottle'),('pilsner-lager',6,'piece','Six pack'),
  ('guinness-foreign-extra-stout',500,'ml','Bottle'),('guinness-foreign-extra-stout',6,'piece','Six pack'),
  ('heineken-original',330,'ml','Bottle'),('heineken-original',500,'ml','Can'),('desperados-original',330,'ml','Bottle'),('desperados-original',500,'ml','Can'),
  ('bavaria-original',500,'ml','Can'),('corona-extra',330,'ml','Bottle'),('savanna-dry',330,'ml','Bottle'),('hunters-dry',330,'ml','Bottle'),
  ('snapp',300,'ml','Bottle'),('kenyan-originals-craft-cider',330,'ml','Bottle'),
  ('gilbeys-premium-dry-gin',250,'ml','Bottle'),('gilbeys-premium-dry-gin',350,'ml','Bottle'),('gilbeys-premium-dry-gin',750,'ml','Bottle'),
  ('gordons-london-dry-gin',750,'ml','Bottle'),('gordons-london-dry-gin',1,'L','Bottle'),
  ('bombay-sapphire',750,'ml','Bottle'),('bombay-sapphire',1,'L','Bottle'),('beefeater-london-dry-gin',750,'ml','Bottle'),('beefeater-london-dry-gin',1,'L','Bottle'),
  ('hendricks-gin',750,'ml','Bottle'),('hendricks-gin',1,'L','Bottle'),('tanqueray-no-ten',750,'ml','Bottle'),('tanqueray-no-ten',1,'L','Bottle'),
  ('seagrams-extra-dry-gin',750,'ml','Bottle'),('new-amsterdam-gin',750,'ml','Bottle'),('new-amsterdam-gin',1,'L','Bottle'),
  ('bulldog-london-dry-gin',750,'ml','Bottle'),('bulldog-london-dry-gin',1,'L','Bottle'),('chrome-gin',250,'ml','Bottle'),('chrome-gin',750,'ml','Bottle'),('chrome-gin',1,'L','Bottle'),
  ('58-classic-premium-gin',750,'ml','Bottle'),
  ('absolut-original-vodka',750,'ml','Bottle'),('absolut-original-vodka',1,'L','Bottle'),('absolut-vanilia',750,'ml','Bottle'),('absolut-vanilia',1,'L','Bottle'),('absolut-elyx',1,'L','Bottle'),
  ('smirnoff-red-label-vodka',250,'ml','Bottle'),('smirnoff-red-label-vodka',750,'ml','Bottle'),('smirnoff-red-label-vodka',1,'L','Bottle'),
  ('smirnoff-vanilla',750,'ml','Bottle'),('smirnoff-orange',750,'ml','Bottle'),('flirt-green-apple-vodka',750,'ml','Bottle'),('flirt-green-apple-vodka',1,'L','Bottle'),
  ('flirt-red-vodka',750,'ml','Bottle'),('flirt-red-vodka',1,'L','Bottle'),('class-21-vodka',750,'ml','Bottle'),('ciroc-ultra-premium-vodka',750,'ml','Bottle'),('grey-goose-vodka',750,'ml','Bottle'),
  ('hennessy-vs',700,'ml','Bottle'),('hennessy-vs',1,'L','Bottle'),('hennessy-vsop',700,'ml','Bottle'),('hennessy-vsop',1,'L','Bottle'),('hennessy-xo',700,'ml','Bottle'),
  ('martell-vs',700,'ml','Bottle'),('martell-vs',1,'L','Bottle'),('martell-vsop',700,'ml','Bottle'),('martell-vsop',1,'L','Bottle'),('martell-cordon-bleu',750,'ml','Bottle'),('martell-xo',700,'ml','Bottle'),
  ('courvoisier-vs',700,'ml','Bottle'),('courvoisier-vs',1,'L','Bottle'),('courvoisier-vsop',750,'ml','Bottle'),('courvoisier-vsop',1,'L','Bottle'),('courvoisier-xo',700,'ml','Bottle'),('remy-martin-vsop',700,'ml','Bottle'),
  ('johnnie-walker-red-label',250,'ml','Bottle'),('johnnie-walker-red-label',375,'ml','Bottle'),('johnnie-walker-red-label',750,'ml','Bottle'),('johnnie-walker-red-label',1,'L','Bottle'),
  ('johnnie-walker-black-label',375,'ml','Bottle'),('johnnie-walker-black-label',750,'ml','Bottle'),('johnnie-walker-black-label',1,'L','Bottle'),('johnnie-walker-double-black',1,'L','Bottle'),
  ('johnnie-walker-gold-label-reserve',750,'ml','Bottle'),('johnnie-walker-blue-label',750,'ml','Bottle'),
  ('jameson-irish-whiskey',250,'ml','Bottle'),('jameson-irish-whiskey',350,'ml','Bottle'),('jameson-irish-whiskey',750,'ml','Bottle'),('jameson-irish-whiskey',1,'L','Bottle'),
  ('jack-daniels-old-no-7',350,'ml','Bottle'),('jack-daniels-old-no-7',700,'ml','Bottle'),('jack-daniels-old-no-7',1,'L','Bottle'),
  ('william-lawsons-blended-scotch',750,'ml','Bottle'),('william-lawsons-blended-scotch',1,'L','Bottle'),('william-lawsons-blended-scotch',1.5,'L','Bottle'),
  ('glenfiddich-12-year-old',750,'ml','Bottle'),('glenfiddich-12-year-old',1,'L','Bottle'),('glenfiddich-18-year-old',700,'ml','Bottle'),('glenfiddich-21-year-old',750,'ml','Bottle'),
  ('glenmorangie-the-original',750,'ml','Bottle'),('glenmorangie-the-original',1,'L','Bottle'),('glenmorangie-lasanta',700,'ml','Bottle'),('glenmorangie-quinta-ruban',700,'ml','Bottle'),('glenmorangie-quinta-ruban',1,'L','Bottle'),('glenmorangie-18-year-old',700,'ml','Bottle'),
  ('chivas-regal-12',750,'ml','Bottle'),('chivas-regal-12',1,'L','Bottle'),('the-famous-grouse',750,'ml','Bottle'),('black-and-white-whisky',750,'ml','Bottle'),('ballantines-finest',750,'ml','Bottle'),('grants-triple-wood',750,'ml','Bottle'),
  ('all-seasons-premium-whisky',250,'ml','Bottle'),('all-seasons-premium-whisky',375,'ml','Bottle'),('all-seasons-premium-whisky',750,'ml','Bottle'),('all-seasons-premium-whisky',1,'L','Bottle'),
  ('8pm-indian-whisky',750,'ml','Bottle'),('8pm-indian-whisky',1,'L','Bottle'),('whytehall-honey-whiskey',1,'L','Bottle'),
  ('captain-morgan-original-spiced-gold',250,'ml','Bottle'),('captain-morgan-original-spiced-gold',750,'ml','Bottle'),('captain-morgan-original-spiced-gold',1,'L','Bottle'),('captain-morgan-black-spiced',1,'L','Bottle'),
  ('bacardi-carta-blanca',750,'ml','Bottle'),('bacardi-carta-blanca',1,'L','Bottle'),('bacardi-carta-oro',750,'ml','Bottle'),('bacardi-carta-oro',1,'L','Bottle'),('bacardi-carta-negra',750,'ml','Bottle'),('bacardi-carta-negra',1,'L','Bottle'),
  ('malibu-original',750,'ml','Bottle'),('malibu-original',1,'L','Bottle'),('old-monk-the-legend',750,'ml','Bottle'),('myerss-original-dark',750,'ml','Bottle'),('myerss-original-dark',1,'L','Bottle'),('lambs-navy-rum',750,'ml','Bottle'),('lambs-navy-rum',1,'L','Bottle'),('afri-bull-cafe-rum',1,'L','Bottle'),
  ('jose-cuervo-especial-gold',750,'ml','Bottle'),('jose-cuervo-especial-gold',1,'L','Bottle'),('jose-cuervo-especial-silver',750,'ml','Bottle'),('jose-cuervo-especial-silver',1,'L','Bottle'),
  ('olmeca-gold',750,'ml','Bottle'),('olmeca-blanco',750,'ml','Bottle'),('sierra-gold',750,'ml','Bottle'),('sierra-silver',750,'ml','Bottle'),('camino-real-gold',750,'ml','Bottle'),('camino-real-blanco',750,'ml','Bottle'),('patron-silver',750,'ml','Bottle'),('don-julio-anejo',750,'ml','Bottle'),
  ('amarula-cream',750,'ml','Bottle'),('amarula-cream',1,'L','Bottle'),('baileys-original-irish-cream',750,'ml','Bottle'),('baileys-original-irish-cream',1,'L','Bottle'),('kahlua-coffee-liqueur',750,'ml','Bottle'),('kahlua-coffee-liqueur',1,'L','Bottle'),
  ('tia-maria-coffee-liqueur',1,'L','Bottle'),('southern-comfort-original',750,'ml','Bottle'),('southern-comfort-original',1,'L','Bottle'),('sheridans-coffee-layered-liqueur',1,'L','Bottle'),('tequila-rose-strawberry-cream',700,'ml','Bottle'),
  ('4th-street-sweet-rose',750,'ml','Bottle'),('4th-street-sweet-rose',1.5,'L','Bottle'),('4th-street-sweet-red',750,'ml','Bottle'),('4th-street-sweet-white',750,'ml','Bottle'),
  ('belaire-brut',750,'ml','Bottle'),('belaire-rare-rose',750,'ml','Bottle'),('four-cousins-sweet-red',750,'ml','Bottle'),('four-cousins-sweet-white',750,'ml','Bottle'),('drostdy-hof-claret-select',750,'ml','Bottle'),('nederburg-barone',750,'ml','Bottle'),('namaqua-sweet-red',750,'ml','Bottle'),
  ('coca-cola-original',330,'ml','Can'),('coca-cola-original',500,'ml','Bottle'),('coca-cola-original',1,'L','Bottle'),('coca-cola-original',2,'L','Bottle'),
  ('coca-cola-light',330,'ml','Can'),('coca-cola-light',1,'L','Bottle'),('coca-cola-light',2,'L','Bottle'),('fanta-orange',330,'ml','Can'),('fanta-orange',1,'L','Bottle'),('fanta-orange',2,'L','Bottle'),
  ('fanta-pineapple',1,'L','Bottle'),('fanta-pineapple',2,'L','Bottle'),('sprite',330,'ml','Can'),('sprite',1,'L','Bottle'),('sprite',2,'L','Bottle'),
  ('schweppes-tonic-water',330,'ml','Can'),('red-bull-energy-drink',250,'ml','Can'),('red-bull-energy-drink',330,'ml','Can'),('monster-energy-original',330,'ml','Can'),('krest-bitter-lemon',300,'ml','Bottle'),('stoney-tangawizi',300,'ml','Bottle'),
  ('william-lawsons-super-spiced',700,'ml','Bottle'),('zafiro-pink-premium-gin',750,'ml','Bottle'),('white-owl-whisky',750,'ml','Bottle'),('whitelace-gin',500,'ml','Bottle'),('johnnie-walker-white-walker',1,'L','Bottle'),
  ('viceroy-5-year-old-brandy',350,'ml','Bottle'),('viceroy-5-year-old-brandy',750,'ml','Bottle'),('viceroy-10-year-old-brandy',750,'ml','Bottle'),('waterproof-blended-malt',1,'L','Bottle'),
  ('vat-69-blended-scotch',375,'ml','Bottle'),('vat-69-blended-scotch',750,'ml','Bottle'),('vat-69-blended-scotch',1,'L','Bottle'),('va-imperial-cream',250,'ml','Bottle'),('va-imperial-cream',750,'ml','Bottle'),('two-keys-whisky',750,'ml','Bottle'),
  ('tullamore-dew',1,'L','Bottle'),('triple-ace-vodka',250,'ml','Bottle'),('ti-white-house-premium-whisky',750,'ml','Bottle'),('three-barrels-vsop',1,'L','Bottle'),('famous-grouse-sherry-cask',750,'ml','Bottle'),
  ('singleton-dufftown-12',750,'ml','Bottle'),('macallan-double-cask-15',750,'ml','Bottle'),('glenlivet-founders-reserve',750,'ml','Bottle'),('glenlivet-founders-reserve',1,'L','Bottle'),('glenlivet-caribbean-reserve',750,'ml','Bottle'),
  ('glenlivet-12',750,'ml','Bottle'),('glenlivet-15',700,'ml','Bottle'),('glenlivet-18',1,'L','Bottle'),('glen-silver-single-malt',700,'ml','Bottle'),('glen-silver-12',700,'ml','Bottle'),
  ('tanqueray-rangpur',700,'ml','Bottle'),('tanqueray-rangpur',1,'L','Bottle'),('tanqueray-london-dry',750,'ml','Bottle'),('tanqueray-london-dry',1,'L','Bottle'),('tanqueray-blackcurrant-royale',1,'L','Bottle'),
  ('teachers-highland-cream',750,'ml','Bottle'),('teachers-highland-cream',1,'L','Bottle'),('teremana-tequila',750,'ml','Bottle'),('st-remy-vsop',700,'ml','Bottle'),('st-remy-xo',750,'ml','Bottle'),('strawberry-lips',750,'ml','Bottle'),
  ('strettons-original-dry-gin',750,'ml','Bottle'),('strettons-triple-berry',750,'ml','Bottle'),('strettons-wild-berries',750,'ml','Bottle'),('smirnoff-black-ice',330,'ml','Can'),('smirnoff-blue-vodka',750,'ml','Bottle'),('smirnoff-ice-pineapple-punch',330,'ml','Can'),
  ('scots-gold-black',750,'ml','Bottle'),('scots-gold-black',1,'L','Bottle'),('scots-gold-8',750,'ml','Bottle'),('scots-gold-12',750,'ml','Bottle'),('scots-gold-red',1,'L','Bottle'),('sheridans-coffee-layered-liqueur',500,'ml','Bottle'),
  ('shustoff-old-history',500,'ml','Bottle'),('silver-anchor-dry-gin',750,'ml','Bottle'),('singleton-15',700,'ml','Bottle'),('singleton-18',700,'ml','Bottle'),('sir-edwards-blended-scotch',750,'ml','Bottle'),('sir-edwards-blended-scotch',1,'L','Bottle'),
  ('six-dogs-blue-gin',750,'ml','Bottle'),('royal-stag-superior',750,'ml','Bottle'),('rose-dargent-pink-strawberry',750,'ml','Bottle'),('southern-comfort-original',350,'ml','Bottle'),('southern-comfort-original',700,'ml','Bottle'),
  ('1659-classic-red',750,'ml','Bottle'),('7-hills-natural-sweet-white',750,'ml','Bottle'),('zapallares-sauvignon-blanc',1.5,'L','Bottle'),
  ('welmoed-shiraz',750,'ml','Bottle'),('welmoed-pinotage',750,'ml','Bottle'),('welmoed-rose',750,'ml','Bottle'),('welmoed-pinot-grigio',750,'ml','Bottle'),('welmoed-chenin-blanc',750,'ml','Bottle'),('welmoed-chardonnay',750,'ml','Bottle'),('welmoed-merlot',750,'ml','Bottle'),
  ('veuve-du-vernay-brut-rose',750,'ml','Bottle'),('veuve-du-vernay-ice',750,'ml','Bottle'),('veuve-du-vernay-brut',750,'ml','Bottle'),('veuve-ambal-brut',750,'ml','Bottle'),('veuve-ambal-rose-brut',750,'ml','Bottle'),
  ('tilia-malbec',750,'ml','Bottle'),('tocornal-merlot',750,'ml','Bottle'),('tocornal-chardonnay',1.5,'L','Bottle'),('tocornal-sauvignon-blanc',1.5,'L','Bottle'),('the-guvnor-red',750,'ml','Bottle'),('the-guvnor-white',750,'ml','Bottle'),
  ('taittinger-prestige-rose',750,'ml','Bottle'),('taittinger-brut-reserve',750,'ml','Bottle'),('soupcon-rose-danjou',750,'ml','Bottle'),('soupcon-rose-de-loire',750,'ml','Bottle'),
  ('signore-giuseppe-prosecco',750,'ml','Bottle'),('signore-giuseppe-prosecco-rose',750,'ml','Bottle'),('samatha-sweet-white',750,'ml','Bottle'),('samatha-rose',750,'ml','Bottle'),
  ('rooiberg-natural-sweet-rose',750,'ml','Bottle'),('rooiberg-natural-sweet-red',750,'ml','Bottle'),('rooiberg-colombar',750,'ml','Bottle'),
  ('rosso-nobile-espresso',750,'ml','Bottle'),('rosso-nobile-cherry',750,'ml','Bottle'),('rosso-nobile-chocolate',750,'ml','Bottle'),('rosso-nobile-nougat',750,'ml','Bottle'),('rosso-nobile-raspberry-lemon',750,'ml','Bottle'),('rosso-bianco-vaniglia',750,'ml','Bottle'),
  ('rust-en-vrede-syrah',750,'ml','Bottle'),('rendez-vous-sparkling-white-grape',750,'ml','Bottle'),('rendez-vous-sparkling-apple',750,'ml','Bottle'),('rendez-vous-sparkling-blue',750,'ml','Bottle'),
  ('robertson-sweet-white',750,'ml','Bottle'),('robertson-sweet-red-sparkling',750,'ml','Bottle'),('robertson-red',1.5,'L','Bottle'),('robertson-sweet-rose',750,'ml','Bottle'),
  ('pierre-marcel-sweet-rose',750,'ml','Bottle'),('pierre-marcel-sweet-red',750,'ml','Bottle'),('pierre-marcel-sweet-red',1.5,'L','Bottle'),('pierre-marcel-sweet-white',750,'ml','Bottle'),
  ('poeti-prosecco-doc-rose',750,'ml','Bottle'),('pierre-jourdan-belle-rose',750,'ml','Bottle'),('pierre-jourdan-brut',750,'ml','Bottle'),('olepasu-white',750,'ml','Bottle'),('olepasu-red-dry',750,'ml','Bottle'),
  ('nederburg-shiraz',750,'ml','Bottle'),('nederburg-pinotage',750,'ml','Bottle'),('nederburg-merlot',750,'ml','Bottle'),('nederburg-cabernet-sauvignon',750,'ml','Bottle'),('nederburg-sauvignon-blanc',750,'ml','Bottle'),
  ('mulderbosch-sparkling-rose',750,'ml','Bottle'),('mulderbosch-chenin-blanc-sparkling',750,'ml','Bottle'),('mulderbosch-cabernet-rose',750,'ml','Bottle'),('mucho-mas-red',750,'ml','Bottle'),('mucho-mas-white',1.5,'L','Bottle'),
  ('moet-chandon-brut-imperial',750,'ml','Bottle'),('moet-chandon-brut-imperial',1.5,'L','Bottle'),('moet-chandon-brut-imperial',3,'L','Bottle'),('moet-chandon-nectar-imperial',750,'ml','Bottle'),
  ('mohans-reserve-sweet-white',750,'ml','Bottle'),('martini-dolce-zero',750,'ml','Bottle'),('mikado-lychee',700,'ml','Bottle'),('mikado-passion-fruit',700,'ml','Bottle'),('mikado-cherry',700,'ml','Bottle'),('mikado-pineapple',700,'ml','Bottle'),
  ('mateus-original-rose',750,'ml','Bottle'),('chapoutier-belleruche-white',750,'ml','Bottle'),('chapoutier-la-ciboise-rouge',750,'ml','Bottle'),('leopards-leap-cabernet-merlot',750,'ml','Bottle'),('leopards-leap-merlot',750,'ml','Bottle'),('le-filou-sweet-rouge',750,'ml','Bottle'),('la-motte-pierneef-syrah-viognier',750,'ml','Bottle'),
  ('4th-street-sweet-red',5,'L','Cask'),('belaire-rare-rose',1.5,'L','Bottle')
)
insert into public.catalog_product_variants (catalog_product_id, volume_value, volume_unit, package_type)
select cp.id, vd.volume_value, vd.volume_unit, vd.package_type
from variant_data vd
join public.catalog_products cp on cp.slug = vd.slug
on conflict (catalog_product_id, volume_value, volume_unit, package_type)
do update set active = true, updated_at = now();
