-- Expand the Kenya catalog from individually reviewed Nairobi Drinks listings.
-- Product identity and sellable formats are global. Shop stock, purchase prices
-- and selling prices remain private and are never seeded by this migration.
-- This migration is additive and safe to rerun.

with families(slug, name, brand, category, keywords) as (values
  ('6th-sense-gin-london-dry-gin','6th sense gin london dry gin','6th Sense','gin',array['6th sense','6th sense gin london dry gin','gin']),
  ('absolut-pears','Absolut pears','Absolut','vodka',array['absolut','absolut pears','vodka']),
  ('agavita-platinum-blanco','Agavita platinum blanco','agavita','tequila',array['agavita','agavita platinum blanco','tequila']),
  ('albert-jarraund-vs','Albert jarraund vs','Albert Jarraund','cognac',array['albert jarraund','albert jarraund vs','cognac']),
  ('alize-bleu-passion','Alize Bleu Passion','Alize','liqueur',array['alize','alize bleu passion','liqueur']),
  ('alize-wild-passion','Alize Wild Passion','Alize','liqueur',array['alize','alize wild passion','liqueur']),
  ('angostura-bitters','Angostura bitters','Angostura','liqueur',array['angostura','angostura bitters','liqueur']),
  ('angostura-reserva-3-years','Angostura Reserva 3 Years','Angostura','rum',array['angostura','angostura reserva 3 years','rum']),
  ('apaltagua-gran-verano-rosado-carmenere','Apaltagua gran verano rosado carmenere','Gran Verano','wine',array['gran verano','apaltagua gran verano rosado carmenere','wine']),
  ('aperol','Aperol','Aperol','liqueur',array['aperol','liqueur']),
  ('arak-haddad-silver-label','Arak haddad silver label','arak','brandy',array['arak','arak haddad silver label','brandy']),
  ('arbor-mist-chardonnay-tropical-fruits','Arbor mist chardonnay tropical fruits','Arbor Mist','wine',array['arbor mist','arbor mist chardonnay tropical fruits','wine']),
  ('archers-peach','Archers peach','Archers Peach','liqueur',array['archers peach','liqueur']),
  ('ardmore-legacy','Ardmore legacy','Ardmore','whisky',array['ardmore','ardmore legacy','whisky']),
  ('bacardi-breezer-lime','Bacardi breezer lime','Bacardi','ready-to-drink',array['bacardi','bacardi breezer lime','ready-to-drink']),
  ('bacardi-breezer-peach','Bacardi breezer peach','Bacardi','ready-to-drink',array['bacardi','bacardi breezer peach','ready-to-drink']),
  ('bacardi-breezer-pineapple','Bacardi breezer pineapple','Bacardi','ready-to-drink',array['bacardi','bacardi breezer pineapple','ready-to-drink']),
  ('bacardi-breezer-watermelon','Bacardi breezer watermelon','Bacardi','ready-to-drink',array['bacardi','bacardi breezer watermelon','ready-to-drink']),
  ('balozi','Balozi','Balozi','beer',array['balozi','beer']),
  ('bardinet-vsop','Bardinet vsop','Bardinet','brandy',array['bardinet','bardinet vsop','brandy']),
  ('bavaria-smalt-original-zero','Bavaria smalt original zero','Bavaria','non-alcoholic',array['bavaria','bavaria smalt original zero','non-alcoholic']),
  ('beehive-honey-brandy','Beehive honey brandy','Beehive','brandy',array['beehive','beehive honey brandy','brandy']),
  ('beehive-vsop-brandy','Beehive vsop brandy','Beehive','brandy',array['beehive','beehive vsop brandy','brandy']),
  ('belaire-brut-fantome','Belaire brut fantome','Belaire','wine',array['belaire','belaire brut fantome','wine']),
  ('belaire-luxe-fantome','Belaire luxe fantome','Belaire','wine',array['belaire','belaire luxe fantome','wine']),
  ('belaire-luxe-rose','Belaire luxe rose','Belaire','wine',array['belaire','belaire luxe rose','wine']),
  ('belaire-luxe-rose-fantome','Belaire luxe rose fantome','Belaire','wine',array['belaire','belaire luxe rose fantome','wine']),
  ('belaire-rose-fantome','Belaire rose fantome','Belaire','wine',array['belaire','belaire rose fantome','wine']),
  ('bells-blended-scotch-whisky','Bells blended scotch whisky','Bells','whisky',array['bells','bells blended scotch whisky','whisky']),
  ('best-whisky','Best whisky','Best Whisky','whisky',array['best whisky','whisky']),
  ('bisquit-vs-classique','Bisquit vs classique','Bisquit','cognac',array['bisquit','bisquit vs classique','cognac']),
  ('black-bird-sweet-red','Black Bird Sweet Red','Black Bird','wine',array['black bird','black bird sweet red','wine']),
  ('black-bird-sweet-rose','Black Bird Sweet Rose','Black Bird','wine',array['black bird','black bird sweet rose','wine']),
  ('black-bird-sweet-white','Black Bird Sweet White','Black Bird','wine',array['black bird','black bird sweet white','wine']),
  ('bleu-dargent-london-dry-gin','Bleu d''argent london dry gin','Bleu','gin',array['bleu','bleu d''argent london dry gin','gin']),
  ('bond-7','Bond 7','Bond 7','whisky',array['bond 7','whisky']),
  ('borghetti-cafe-espresso','Borghetti Cafe Espresso','Borghetti','liqueur',array['borghetti','borghetti cafe espresso','liqueur']),
  ('bowmore-15-years','Bowmore 15 Years','Bowmore','whisky',array['bowmore','bowmore 15 years','whisky']),
  ('buffalo-trace-kentucky-straight-bourbon-whiskey','Buffalo trace kentucky straight bourbon whiskey','Buffalo Trace','whisky',array['buffalo trace','buffalo trace kentucky straight bourbon whiskey','whisky']),
  ('bulleit-bourbon','Bulleit bourbon','Bulleit Bourbon','whisky',array['bulleit bourbon','whisky']),
  ('bushmills-red-bush','Bushmills red bush','Bushmills','whisky',array['bushmills','bushmills red bush','whisky']),
  ('cachaca-51-brazil','Cachaca 51 brazil','Cachaca','cachaca',array['cachaca','cachaca 51 brazil']),
  ('cachaca-sagatiba-pura','Cachaca sagatiba pura','Cachaca','cachaca',array['cachaca','cachaca sagatiba pura']),
  ('campari-negroni','Campari negroni','Campari','liqueur',array['campari','campari negroni','liqueur']),
  ('captain-morgan-white-spiced-rum','Captain morgan white spiced rum','Captain Morgan','rum',array['captain morgan','captain morgan white spiced rum','rum']),
  ('carlo-rossi-red-sweet','Carlo rossi red sweet','Carlo Rossi','wine',array['carlo rossi','carlo rossi red sweet','wine']),
  ('carlo-rossi-sangria','Carlo rossi sangria','Carlo Rossi','wine',array['carlo rossi','carlo rossi sangria','wine']),
  ('casal-mendes-blue','Casal mendes blue','casal mendes','wine',array['casal mendes','casal mendes blue','wine']),
  ('cellar-cask-sweet-red','Cellar cask sweet red','Cellar Cask','wine',array['cellar cask','cellar cask sweet red','wine']),
  ('cellar-cask-white-sweet','Cellar cask white sweet','Cellar Cask','wine',array['cellar cask','cellar cask white sweet','wine']),
  ('chamdor-red-non-alcoholic-wine','Chamdor red (non-alcoholic wine)','Chamdor','wine',array['chamdor','chamdor red (non-alcoholic wine)','wine']),
  ('chamdor-white-non-alcoholic-wine','Chamdor white (non-alcoholic-wine)','Chamdor','wine',array['chamdor','chamdor white (non-alcoholic-wine)','wine']),
  ('chivas-regal-18-years','Chivas regal 18 years','Chivas Regal','whisky',array['chivas regal','chivas regal 18 years','whisky']),
  ('claymore-blended-scotch-whisky','Claymore blended scotch whisky','Claymore','whisky',array['claymore','claymore blended scotch whisky','whisky']),
  ('cockburns-fine-ruby','Cockburns fine ruby','cockburns','wine',array['cockburns','cockburns fine ruby','wine']),
  ('cockburns-special-reserve','Cockburns special reserve','cockburns','wine',array['cockburns','cockburns special reserve','wine']),
  ('courvoisier-vsop-tripple-oak','Courvoisier vsop tripple oak','Courvoisier','cognac',array['courvoisier','courvoisier vsop tripple oak','cognac']),
  ('culemborg-cape-red','Culemborg cape red','Culemborg','wine',array['culemborg','culemborg cape red','wine']),
  ('cutty-sark','Cutty sark','Cutty Sark','whisky',array['cutty sark','whisky']),
  ('dalwhinnie-15-years','Dalwhinnie 15 years','Dalwhinnie','whisky',array['dalwhinnie','dalwhinnie 15 years','whisky']),
  ('dead-mans-finger-coffee-rum','Dead man''s finger coffee rum','Dead','rum',array['dead','dead man''s finger coffee rum','rum']),
  ('dead-mans-fingers-coconut-rum','Dead man''s fingers coconut rum','Dead','rum',array['dead','dead man''s fingers coconut rum','rum']),
  ('don-montego','Don montego','Don Montego','brandy',array['don montego','brandy']),
  ('drostdy-hof-premier-grand-cru-white-dry','Drostdy-hof premier grand cru white dry','Drostdy Hof','wine',array['drostdy hof','drostdy-hof premier grand cru white dry','wine']),
  ('drostdy-hof-white-sweet','Drostdy-hof white sweet','Drostdy Hof','wine',array['drostdy hof','drostdy-hof white sweet','wine']),
  ('early-times-kentucky-straight-bourbon-whisky','Early Times Kentucky Straight Bourbon Whisky','Early Times','whisky',array['early times','early times kentucky straight bourbon whisky','whisky']),
  ('el-charro-gold','El charro gold','El Charro','tequila',array['el charro','el charro gold','tequila']),
  ('el-charro-silver','El charro silver','El Charro','tequila',array['el charro','el charro silver','tequila']),
  ('el-jimador-blanco','El jimador blanco','Jimador','tequila',array['jimador','el jimador blanco','tequila']),
  ('el-jimador-reposado','El jimador reposado','Jimador','tequila',array['jimador','el jimador reposado','tequila']),
  ('elephant-handcrafted-london-dry-gin','Elephant Handcrafted London Dry Gin','Elephant Gin','gin',array['elephant gin','elephant handcrafted london dry gin','gin']),
  ('finlandia-blackcurrant','Finlandia blackcurrant','Finlandia','vodka',array['finlandia','finlandia blackcurrant','vodka']),
  ('finlandia-grapefruit','Finlandia grapefruit','Finlandia','vodka',array['finlandia','finlandia grapefruit','vodka']),
  ('finlandia-vodka-original','Finlandia vodka original','Finlandia','vodka',array['finlandia','finlandia vodka original','vodka']),
  ('firewater-cinnamon','Firewater cinnamon','Firewater','whisky',array['firewater','firewater cinnamon','whisky']),
  ('flirt-vodka-golden-apple','Flirt vodka golden apple','Flirt Vodka','vodka',array['flirt vodka','flirt vodka golden apple','vodka']),
  ('flirt-vodka-orange','Flirt vodka orange','Flirt Vodka','vodka',array['flirt vodka','flirt vodka orange','vodka']),
  ('four-cousins-chardonnay','Four cousins chardonnay','Four Cousins','wine',array['four cousins','four cousins chardonnay','wine']),
  ('fragolino-bianco-morando','Fragolino bianco morando','Fragolino','wine',array['fragolino','fragolino bianco morando','wine']),
  ('frontera-caberbet-sauvignon','Frontera caberbet sauvignon','Frontera','wine',array['frontera','frontera caberbet sauvignon','wine']),
  ('frontera-chardonnay','Frontera chardonnay','Frontera','wine',array['frontera','frontera chardonnay','wine']),
  ('frontera-merlot','Frontera merlot','Frontera','wine',array['frontera','frontera merlot','wine']),
  ('frontera-pinot-grigio','Frontera Pinot Grigio','Frontera','wine',array['frontera','frontera pinot grigio','wine']),
  ('frontera-sauvignon-blanc','Frontera sauvignon blanc','Frontera','wine',array['frontera','frontera sauvignon blanc','wine']),
  ('frontera-shiraz','Frontera shiraz','Frontera','wine',array['frontera','frontera shiraz','wine']),
  ('frontera-sparkling-moscato','Frontera Sparkling Moscato','Frontera','wine',array['frontera','frontera sparkling moscato','wine']),
  ('frontera-sparkling-rose','Frontera Sparkling Rose','Frontera','wine',array['frontera','frontera sparkling rose','wine']),
  ('frontera-sweet-red','Frontera Sweet Red','Frontera','wine',array['frontera','frontera sweet red','wine']),
  ('fundador-solera-reserva','Fundador solera reserva','Fundador Brandy','brandy',array['fundador brandy','fundador solera reserva','brandy']),
  ('gato-negro-cabernet-merlot','Gato negro cabernet merlot','Gato Negro','wine',array['gato negro','gato negro cabernet merlot','wine']),
  ('gato-negro-cabernet-sauvignon','Gato negro cabernet sauvignon','Gato Negro','wine',array['gato negro','gato negro cabernet sauvignon','wine']),
  ('gato-negro-chardonnay','Gato negro chardonnay','Gato Negro','wine',array['gato negro','gato negro chardonnay','wine']),
  ('gato-negro-merlot','Gato negro merlot','Gato Negro','wine',array['gato negro','gato negro merlot','wine']),
  ('gato-negro-sauvignon-blanc','Gato negro sauvignon blanc','Gato Negro','wine',array['gato negro','gato negro sauvignon blanc','wine']),
  ('gato-negro-shiraz','Gato negro shiraz','Gato Negro','wine',array['gato negro','gato negro shiraz','wine']),
  ('gibsons-pink-premium-gin','Gibsons pink premium gin','Gibsons','gin',array['gibsons','gibsons pink premium gin','gin']),
  ('glen-silvers','Glen silvers','Glen Silvers','whisky',array['glen silvers','whisky']),
  ('glenlivet-12-years-double-oak','Glenlivet 12 years double oak','Glenlivet','whisky',array['glenlivet','glenlivet 12 years double oak','whisky']),
  ('gordons-pink-gin','Gordon''s pink gin','Gordon''s','gin',array['gordon''s','gordon''s pink gin','gin']),
  ('grants-signature','Grants signature','Grant''s','whisky',array['grant''s','grants signature','whisky']),
  ('h-by-hine-vsop','H by hine vsop','Hine','cognac',array['hine','h by hine vsop','cognac']),
  ('harveys-bristol-cream-sherry','Harveys bristol cream sherry','Harveys Bristol','wine',array['harveys bristol','harveys bristol cream sherry','wine']),
  ('heineken-zero','Heineken Zero','Heineken','non-alcoholic',array['heineken','heineken zero','non-alcoholic']),
  ('hennessy-masters-blend','Hennessy masters blend','hennessy','cognac',array['hennessy','hennessy masters blend','cognac']),
  ('hine-rare','Hine rare','Hine','cognac',array['hine','hine rare','cognac']),
  ('hunters-gold','Hunters gold','Hunter''s','cider',array['hunter''s','hunters gold','cider']),
  ('j-and-b-honey','J&B Honey','J&B','whisky',array['j&b','j&b honey','whisky']),
  ('j-and-b-rare','J&B rare','J&B','whisky',array['j&b','j&b rare','whisky']),
  ('jack-daniels-apple','Jack Daniel''s Apple','Jack Daniels','whisky',array['jack daniels','jack daniel''s apple','whisky']),
  ('jack-daniels-honey','Jack daniels honey','Jack Daniels','liqueur',array['jack daniels','jack daniels honey','liqueur']),
  ('jack-daniels-tennessee-cola','Jack Daniels Tennessee Cola','Jack Daniels','whisky',array['jack daniels','jack daniels tennessee cola','whisky']),
  ('jack-daniels-tennessee-fire','Jack daniel''s tennessee fire','Jack Daniels','liqueur',array['jack daniels','jack daniel''s tennessee fire','liqueur']),
  ('jack-daniels-tennessee-fire-liqueur','Jack daniels tennessee fire (Liqueur)','Jack Daniels','whisky',array['jack daniels','jack daniels tennessee fire (liqueur)','whisky']),
  ('jack-daniels-tennessee-rye','Jack daniels tennessee rye','Jack Daniels','whisky',array['jack daniels','jack daniels tennessee rye','whisky']),
  ('jagermeister','Jagermeister','Jagermeister','liqueur',array['jagermeister','liqueur']),
  ('jim-beam','Jim beam','Jim Beam','whisky',array['jim beam','whisky']),
  ('jim-beam-apple','Jim beam apple','Jim Beam','liqueur',array['jim beam','jim beam apple','liqueur']),
  ('jim-beam-apple-liqueur','Jim beam apple (liqueur)','Jim Beam','whisky',array['jim beam','jim beam apple (liqueur)','whisky']),
  ('jim-beam-honey-liqueur','Jim beam honey (liqueur)','Jim Beam','whisky',array['jim beam','jim beam honey (liqueur)','whisky']),
  ('jim-beam-red-stag','Jim beam red stag','Jim Beam','liqueur',array['jim beam','jim beam red stag','liqueur']),
  ('jim-beam-red-stag-liqueur','Jim beam red stag (liqueur)','Jim Beam','whisky',array['jim beam','jim beam red stag (liqueur)','whisky']),
  ('jim-beam-signature-craft','Jim beam signature craft','Jim Beam','whisky',array['jim beam','jim beam signature craft','whisky']),
  ('john-bannermans','John Bannerman''s','John Bannerman','whisky',array['john bannerman','john bannerman''s','whisky']),
  ('john-barr','John Barr','John Barr','whisky',array['john barr','whisky']),
  ('jp-chenet-apple','Jp chenet apple','JP Chenet Wine','wine',array['jp chenet wine','jp chenet apple','wine']),
  ('jp-chenet-pineapple','Jp chenet pineapple','JP Chenet Wine','wine',array['jp chenet wine','jp chenet pineapple','wine']),
  ('jp-chenet-strawberry-and-raspberry','Jp chenet strawberry and raspberry','JP Chenet Wine','wine',array['jp chenet wine','jp chenet strawberry and raspberry','wine']),
  ('jura-16','Jura 16','Jura','whisky',array['jura','jura 16','whisky']),
  ('jura-16-years','Jura 16 years','Jura','whisky',array['jura','jura 16 years','whisky']),
  ('karibrew-craft-beer','Karibrew craft beer','Karibrew','beer',array['karibrew','karibrew craft beer','beer']),
  ('kensington','Kensington','Kensington','gin',array['kensington','gin']),
  ('kwv-3-years','Kwv 3 years','KWV Brandy','brandy',array['kwv brandy','kwv 3 years','brandy']),
  ('kwv-cruxland-black-winter-gin','Kwv cruxland black winter gin','KWV Brandy','gin',array['kwv brandy','kwv cruxland black winter gin','gin']),
  ('lambrusco-dellemilia-amabile-bianco','Lambrusco dell''emilia amabile bianco','Lambrusco','wine',array['lambrusco','lambrusco dell''emilia amabile bianco','wine']),
  ('larios-12','Larios 12','Larios','gin',array['larios','larios 12','gin']),
  ('larios-dry-gin','Larios Dry Gin','Larios','gin',array['larios','larios dry gin','gin']),
  ('larios-rose','Larios Rose','Larios','gin',array['larios','larios rose','gin']),
  ('lauders-blended-scotch-whisky','Lauders blended scotch whisky','Lauders','whisky',array['lauders','lauders blended scotch whisky','whisky']),
  ('leffe','Leffe','Leffe','beer',array['leffe','beer']),
  ('leleshwa-rose','Leleshwa rose','leleshwa','wine',array['leleshwa','leleshwa rose','wine']),
  ('leleshwa-sauvignon-blanc','Leleshwa sauvignon blanc','leleshwa','wine',array['leleshwa','leleshwa sauvignon blanc','wine']),
  ('leleshwa-white-dry','Leleshwa White dry','leleshwa','wine',array['leleshwa','leleshwa white dry','wine']),
  ('limoncello-caducale','Limoncello caducale','Limoncello','liqueur',array['limoncello','limoncello caducale','liqueur']),
  ('limoncello-di-capri','Limoncello di capri','Limoncello','liqueur',array['limoncello','limoncello di capri','liqueur']),
  ('lombard-gold-label','Lombard Gold Label','Lombard','whisky',array['lombard','lombard gold label','whisky']),
  ('los-cabos-gold','Los cabos gold','Los','tequila',array['los','los cabos gold','tequila']),
  ('los-cabos-silver','Los cabos silver','Los','tequila',array['los','los cabos silver','tequila']),
  ('malfy-con-arancia','Malfy con arancia','Malfy','gin',array['malfy','malfy con arancia','gin']),
  ('malfy-con-gin-rosa','Malfy con gin rosa','Malfy','gin',array['malfy','malfy con gin rosa','gin']),
  ('malfy-con-limone','Malfy con limone','Malfy','gin',array['malfy','malfy con limone','gin']),
  ('malibu-black','Malibu Black','Malibu','rum',array['malibu','malibu black','rum']),
  ('mamma-mia-red-sweet','Mamma mia red sweet','mamma mia','wine',array['mamma mia','mamma mia red sweet','wine']),
  ('manyatta-beer','Manyatta beer','Manyatta','beer',array['manyatta','manyatta beer','beer']),
  ('mara-nyekundu','Mara nyekundu','mara','wine',array['mara','mara nyekundu','wine']),
  ('mara-nyeupe','Mara nyeupe','mara','wine',array['mara','mara nyeupe','wine']),
  ('marshalls-bourbon-whiskey','Marshall''s bourbon whiskey','Marshall''s','whisky',array['marshall''s','marshall''s bourbon whiskey','whisky']),
  ('martini-extra-dry','Martini extra dry','martini','wine',array['martini','martini extra dry','wine']),
  ('meukow-vs','Meukow vs','Meukow','cognac',array['meukow','meukow vs','cognac']),
  ('monkey-shoulder','Monkey shoulder','Monkey Shoulder','whisky',array['monkey shoulder','whisky']),
  ('myers-rum','Myers rum','Myers''s Rum','rum',array['myers''s rum','myers rum','rum']),
  ('namaqua-pinotage','Namaqua pinotage','Namaqua','wine',array['namaqua','namaqua pinotage','wine']),
  ('namaqua-rose','Namaqua rose','Namaqua','wine',array['namaqua','namaqua rose','wine']),
  ('namaqua-sweet-white','Namaqua sweet White','Namaqua','wine',array['namaqua','namaqua sweet white','wine']),
  ('negrita-bardinet-rum','Negrita bardinet rum','Negrita','rum',array['negrita','negrita bardinet rum','rum']),
  ('new-grove-silver','New grove silver','New Grove Rum','rum',array['new grove rum','new grove silver','rum']),
  ('new-grove-spiced-rum','New grove spiced rum','New Grove Rum','rum',array['new grove rum','new grove spiced rum','rum']),
  ('oak-wooded-unit-43-gin','(Oak Wooded) Unit 43 Gin','Unit 43','gin',array['unit 43','(oak wooded) unit 43 gin','gin']),
  ('obikwa-cabernet-sauvignon-2016','Obikwa cabernet sauvignon 2016','Obikwa','wine',array['obikwa','obikwa cabernet sauvignon 2016','wine']),
  ('obikwa-pinotage','Obikwa pinotage','Obikwa','wine',array['obikwa','obikwa pinotage','wine']),
  ('odriscoll-irish-whiskey','Odriscoll irish whiskey','Odriscoll','whisky',array['odriscoll','odriscoll irish whiskey','whisky']),
  ('oj-8-5','OJ 8.5','OJ','beer',array['oj','oj 8.5','beer']),
  ('old-nick-golden-rum','Old nick golden rum','Old Nick','rum',array['old nick','old nick golden rum','rum']),
  ('old-nick-white-rum','Old nick white rum','Old Nick','rum',array['old nick','old nick white rum','rum']),
  ('old-smuggler','Old smuggler','Old Smuggler','whisky',array['old smuggler','whisky']),
  ('paddy-irish-whiskey','Paddy Irish Whiskey','Paddy','whisky',array['paddy','paddy irish whiskey','whisky']),
  ('passport-scotch','Passport scotch','Passport Scotch','whisky',array['passport scotch','whisky']),
  ('penasol-sangria','Penasol sangria','Penasol','wine',array['penasol','penasol sangria','wine']),
  ('porto-cruz-tawny','Porto cruz tawny','Porto Cruz','wine',array['porto cruz','porto cruz tawny','wine']),
  ('puianello-primabolla-reggiano-doc-lambrusco','Puianello primabolla reggiano doc lambrusco','Lambrusco','wine',array['lambrusco','puianello primabolla reggiano doc lambrusco','wine']),
  ('remy-martin-club-cognac','Remy martin club cognac','Remy Martins','cognac',array['remy martins','remy martin club cognac','cognac']),
  ('rendez-vous-pink','Rendez vous pink','rendez vous','wine',array['rendez vous','rendez vous pink','wine']),
  ('rendez-vous-red-grape','Rendez vous red grape','rendez vous','wine',array['rendez vous','rendez vous red grape','wine']),
  ('richot','Richot','Richot','brandy',array['richot','brandy']),
  ('saint-celine-sweet-red','Saint celine sweet red','Saint Celine','wine',array['saint celine','saint celine sweet red','wine']),
  ('sandtrap-ipa-craft-beer','SandTrap IPA craft beer','SandTrap','beer',array['sandtrap','sandtrap ipa craft beer','beer']),
  ('santa-helena-dulce','Santa helena dulce','Santa','wine',array['santa','santa helena dulce','wine']),
  ('sauza-tequila-silver','Sauza tequila silver','Sauza','tequila',array['sauza','sauza tequila silver','tequila']),
  ('scottish-leader-original-whisky','Scottish Leader Original Whisky','Scottish Leader','whisky',array['scottish leader','scottish leader original whisky','whisky']),
  ('sikera-apple-cider','Sikera apple cider','Sikera','cider',array['sikera','sikera apple cider','cider']),
  ('skyy-blood-orange','Skyy blood orange','Skyy Vodka','vodka',array['skyy vodka','skyy blood orange','vodka']),
  ('skyy-cherry','Skyy cherry','Skyy Vodka','vodka',array['skyy vodka','skyy cherry','vodka']),
  ('skyy-coconut','Skyy coconut','Skyy Vodka','vodka',array['skyy vodka','skyy coconut','vodka']),
  ('skyy-dragon-fruit','Skyy dragon fruit','Skyy Vodka','vodka',array['skyy vodka','skyy dragon fruit','vodka']),
  ('skyy-ginger','Skyy ginger','Skyy Vodka','vodka',array['skyy vodka','skyy ginger','vodka']),
  ('skyy-grape','Skyy grape','Skyy Vodka','vodka',array['skyy vodka','skyy grape','vodka']),
  ('skyy-passion','Skyy passion','Skyy Vodka','vodka',array['skyy vodka','skyy passion','vodka']),
  ('skyy-raspberry','Skyy raspberry','Skyy Vodka','vodka',array['skyy vodka','skyy raspberry','vodka']),
  ('skyy-vodka','Skyy vodka','Skyy Vodka','vodka',array['skyy vodka','vodka']),
  ('smirnoff-citrus','Smirnoff citrus','smirnoff','vodka',array['smirnoff','smirnoff citrus','vodka']),
  ('smirnoff-espresso','Smirnoff espresso','smirnoff','vodka',array['smirnoff','smirnoff espresso','vodka']),
  ('smirnoff-green-apple','Smirnoff green apple','smirnoff','vodka',array['smirnoff','smirnoff green apple','vodka']),
  ('smirnoff-ice-double-black-with-guarana','Smirnoff ice double black with guarana','smirnoff','ready-to-drink',array['smirnoff','smirnoff ice double black with guarana','ready-to-drink']),
  ('smirnoff-raspberry','Smirnoff raspberry','smirnoff','vodka',array['smirnoff','smirnoff raspberry','vodka']),
  ('sunkissed-natural-sweet-white-wine','Sunkissed natural sweet white wine','Sunkissed Wine','wine',array['sunkissed wine','sunkissed natural sweet white wine','wine']),
  ('tanqueray-flor-de-sevilla-distilled-gin','Tanqueray flor de sevilla distilled gin','Tanqueray','gin',array['tanqueray','tanqueray flor de sevilla distilled gin','gin']),
  ('teeling-whiskey-small-batch','Teeling whiskey small batch','Teeling Whiskey','whisky',array['teeling whiskey','teeling whiskey small batch','whisky']),
  ('tequila-sauza-gold','Tequila sauza gold','Sauza','tequila',array['sauza','tequila sauza gold','tequila']),
  ('the-famous-grouse-smoky-black','The famous grouse smoky black','Famous Grouse','whisky',array['famous grouse','the famous grouse smoky black','whisky']),
  ('the-kraken-black-spiced-rum','The kraken black spiced rum','The','rum',array['the','the kraken black spiced rum','rum']),
  ('the-snow-grouse','The snow grouse','Famous Grouse','whisky',array['famous grouse','the snow grouse','whisky']),
  ('tijuana-sweet-heat','Tijuana sweet heat','Tijuana','tequila',array['tijuana','tijuana sweet heat','tequila']),
  ('tio-pepe-sherry','Tio pepe sherry','sherry wines','wine',array['sherry wines','tio pepe sherry','wine']),
  ('tuborg','Tuborg','Tuborg','beer',array['tuborg','beer']),
  ('tullamore-dew-xo-caribbean-rum-finish','Tullamore Dew Xo Caribbean Rum Finish','Tullamore','whisky',array['tullamore','tullamore dew xo caribbean rum finish','whisky']),
  ('upper-valley-nabygelegen-dry-red','Upper valley nabygelegen dry red','upper valley','wine',array['upper valley','upper valley nabygelegen dry red','wine']),
  ('upper-valley-nabygelegen-sweet-red','Upper valley nabygelegen sweet red','upper valley','wine',array['upper valley','upper valley nabygelegen sweet red','wine']),
  ('upper-valley-nabygelegen-sweet-white','Upper valley nabygelegen sweet white','upper valley','wine',array['upper valley','upper valley nabygelegen sweet white','wine']),
  ('upper-valley-nabygelegen-white-dry','Upper valley nabygelegen white dry','upper valley','wine',array['upper valley','upper valley nabygelegen white dry','wine']),
  ('versus-red-dry','Versus red dry','versus','wine',array['versus','versus red dry','wine']),
  ('versus-sweet-red','Versus sweet red','versus','wine',array['versus','versus sweet red','wine']),
  ('whitley-neil-quince-handcrafted-dry-gin','Whitley neil quince handcrafted dry gin','Whitley','gin',array['whitley','whitley neil quince handcrafted dry gin','gin']),
  ('whitley-neill-gooseberry-gin','Whitley Neill Gooseberry Gin','Whitley','gin',array['whitley','whitley neill gooseberry gin','gin']),
  ('whitley-neill-handcrafted-aloe-and-cucumber-gin','Whitley neill handcrafted aloe & cucumber gin','Whitley','gin',array['whitley','whitley neill handcrafted aloe & cucumber gin','gin']),
  ('whitley-neill-handcrafted-blood-orange-gin','Whitley neill handcrafted blood orange gin','Whitley','gin',array['whitley','whitley neill handcrafted blood orange gin','gin']),
  ('whitley-neill-handcrafted-lemongrass-and-ginger-gin','Whitley neill handcrafted lemongrass & ginger gin','Whitley','gin',array['whitley','whitley neill handcrafted lemongrass & ginger gin','gin']),
  ('whitley-neill-handcrafted-parma-violet-gin','Whitley neill handcrafted parma violet gin','Whitley','gin',array['whitley','whitley neill handcrafted parma violet gin','gin']),
  ('whitley-neill-handcrafted-raspberry-gin','Whitley neill handcrafted raspberry gin','Whitley','gin',array['whitley','whitley neill handcrafted raspberry gin','gin']),
  ('whitley-neill-original-gin','Whitley Neill Original Gin','Whitley','gin',array['whitley','whitley neill original gin','gin']),
  ('whitley-neill-original-handcrafted-dry-gin','Whitley neill original handcrafted dry gin','Whitley','gin',array['whitley','whitley neill original handcrafted dry gin','gin']),
  ('whitley-neill-rhubarb-and-ginger-gin','Whitley Neill Rhubarb & Ginger Gin','Whitley','gin',array['whitley','whitley neill rhubarb & ginger gin','gin']),
  ('whyte-and-mackay','Whyte & mackay','Whyte & Mackay','whisky',array['whyte & mackay','whisky']),
  ('woodford-reserve','Woodford reserve','Woodford Reserve','whisky',array['woodford reserve','whisky'])
)
insert into public.catalog_products (slug, name, brand, category, keywords)
select slug, name, brand, category, keywords
from families
on conflict (slug) do update set
  name = excluded.name,
  brand = excluded.brand,
  category = excluded.category,
  keywords = excluded.keywords,
  active = true,
  updated_at = now();

-- Preserve useful source spellings for families already present in Dukwise.
with aliases(slug, keywords) as (values
  ('amarula-cream',array['amarula fruit cream','amarula']),
  ('bacardi-carta-oro',array['bacardi oro','bacardi']),
  ('bacardi-carta-oro',array['bacardi gold','bacardi']),
  ('ballantines-finest',array['ballantines gift pack','ballantines']),
  ('captain-morgan-original-spiced-gold',array['captain morgan spiced gold - imported','captain morgan']),
  ('ciroc-ultra-premium-vodka',array['ciroc snap frost','ciroc']),
  ('glenlivet-12',array['glenlivet 12 years','glenlivet']),
  ('heineken-original',array['heineken']),
  ('heineken-original',array['heineken']),
  ('jose-cuervo-especial-gold',array['jose cuervo gold','jose cuervo']),
  ('jose-cuervo-especial-silver',array['jose cuervo silver','jose cuervo']),
  ('kenyan-originals-craft-cider',array['ko cider','ko']),
  ('rendez-vous-sparkling-apple',array['rendez vous apple','rendez vous']),
  ('rendez-vous-sparkling-blue',array['rendez vous blue','rendez vous']),
  ('rendez-vous-sparkling-white-grape',array['rendez vous white grape','rendez vous']),
  ('scots-gold-black',array['scots gold black label','scots gold']),
  ('snapp',array['snapp'])
),
expanded as (
  select a.slug, array_agg(distinct keyword order by keyword) as keywords
  from aliases a
  cross join lateral unnest(a.keywords) keyword
  group by a.slug
)
update public.catalog_products cp
set keywords = (
      select array_agg(distinct keyword order by keyword)
      from unnest(cp.keywords || expanded.keywords) keyword
    ),
    active = true,
    updated_at = now()
from expanded
where cp.slug = expanded.slug;

with variant_data(slug, volume_value, volume_unit, package_type) as (values
  ('6th-sense-gin-london-dry-gin',1,'L','Bottle'),
  ('absolut-pears',1,'L','Bottle'),
  ('absolut-pears',750,'ml','Bottle'),
  ('agavita-platinum-blanco',700,'ml','Bottle'),
  ('albert-jarraund-vs',700,'ml','Bottle'),
  ('alize-bleu-passion',1,'L','Bottle'),
  ('alize-bleu-passion',750,'ml','Bottle'),
  ('alize-wild-passion',1,'L','Bottle'),
  ('alize-wild-passion',750,'ml','Bottle'),
  ('amarula-cream',1,'L','Bottle'),
  ('amarula-cream',750,'ml','Bottle'),
  ('angostura-bitters',200,'ml','Bottle'),
  ('angostura-bitters',473,'ml','Bottle'),
  ('angostura-reserva-3-years',750,'ml','Bottle'),
  ('apaltagua-gran-verano-rosado-carmenere',750,'ml','Bottle'),
  ('aperol',1,'L','Bottle'),
  ('aperol',750,'ml','Bottle'),
  ('arak-haddad-silver-label',750,'ml','Bottle'),
  ('arbor-mist-chardonnay-tropical-fruits',750,'ml','Bottle'),
  ('archers-peach',1,'L','Bottle'),
  ('archers-peach',750,'ml','Bottle'),
  ('ardmore-legacy',1,'L','Bottle'),
  ('ardmore-legacy',750,'ml','Bottle'),
  ('bacardi-breezer-lime',6,'piece','Six pack'),
  ('bacardi-breezer-peach',6,'piece','Six pack'),
  ('bacardi-breezer-pineapple',6,'piece','Six pack'),
  ('bacardi-breezer-watermelon',6,'piece','Six pack'),
  ('bacardi-carta-oro',1,'L','Bottle'),
  ('bacardi-carta-oro',750,'ml','Bottle'),
  ('ballantines-finest',750,'ml','Bottle'),
  ('balozi',6,'piece','Six pack'),
  ('bardinet-vsop',750,'ml','Bottle'),
  ('bavaria-smalt-original-zero',6,'piece','Six pack'),
  ('beehive-honey-brandy',1,'L','Bottle'),
  ('beehive-vsop-brandy',1,'L','Bottle'),
  ('belaire-brut-fantome',750,'ml','Bottle'),
  ('belaire-luxe-fantome',750,'ml','Bottle'),
  ('belaire-luxe-rose',750,'ml','Bottle'),
  ('belaire-luxe-rose-fantome',750,'ml','Bottle'),
  ('belaire-rose-fantome',750,'ml','Bottle'),
  ('bells-blended-scotch-whisky',1,'L','Bottle'),
  ('bells-blended-scotch-whisky',750,'ml','Bottle'),
  ('best-whisky',750,'ml','Bottle'),
  ('bisquit-vs-classique',700,'ml','Bottle'),
  ('black-bird-sweet-red',750,'ml','Bottle'),
  ('black-bird-sweet-rose',750,'ml','Bottle'),
  ('black-bird-sweet-white',750,'ml','Bottle'),
  ('bleu-dargent-london-dry-gin',700,'ml','Bottle'),
  ('bond-7',750,'ml','Bottle'),
  ('borghetti-cafe-espresso',1,'L','Bottle'),
  ('borghetti-cafe-espresso',750,'ml','Bottle'),
  ('bowmore-15-years',1,'L','Bottle'),
  ('bowmore-15-years',750,'ml','Bottle'),
  ('buffalo-trace-kentucky-straight-bourbon-whiskey',1,'L','Bottle'),
  ('buffalo-trace-kentucky-straight-bourbon-whiskey',700,'ml','Bottle'),
  ('bulleit-bourbon',1,'L','Bottle'),
  ('bulleit-bourbon',700,'ml','Bottle'),
  ('bushmills-red-bush',750,'ml','Bottle'),
  ('cachaca-51-brazil',1,'L','Bottle'),
  ('cachaca-51-brazil',750,'ml','Bottle'),
  ('cachaca-sagatiba-pura',1,'L','Bottle'),
  ('cachaca-sagatiba-pura',750,'ml','Bottle'),
  ('campari-negroni',1,'L','Bottle'),
  ('campari-negroni',750,'ml','Bottle'),
  ('captain-morgan-original-spiced-gold',1,'L','Bottle'),
  ('captain-morgan-original-spiced-gold',750,'ml','Bottle'),
  ('captain-morgan-white-spiced-rum',1,'L','Bottle'),
  ('captain-morgan-white-spiced-rum',750,'ml','Bottle'),
  ('carlo-rossi-red-sweet',1.5,'L','Bottle'),
  ('carlo-rossi-red-sweet',750,'ml','Bottle'),
  ('carlo-rossi-sangria',1.5,'L','Bottle'),
  ('carlo-rossi-sangria',3,'L','Bottle'),
  ('carlo-rossi-sangria',4,'L','Bottle'),
  ('carlo-rossi-sangria',750,'ml','Bottle'),
  ('casal-mendes-blue',750,'ml','Bottle'),
  ('cellar-cask-sweet-red',750,'ml','Bottle'),
  ('cellar-cask-white-sweet',750,'ml','Bottle'),
  ('chamdor-red-non-alcoholic-wine',750,'ml','Bottle'),
  ('chamdor-white-non-alcoholic-wine',750,'ml','Bottle'),
  ('chivas-regal-18-years',1,'L','Bottle'),
  ('chivas-regal-18-years',750,'ml','Bottle'),
  ('ciroc-ultra-premium-vodka',1,'L','Bottle'),
  ('ciroc-ultra-premium-vodka',3,'L','Bottle'),
  ('ciroc-ultra-premium-vodka',750,'ml','Bottle'),
  ('claymore-blended-scotch-whisky',750,'ml','Bottle'),
  ('cockburns-fine-ruby',1,'L','Bottle'),
  ('cockburns-fine-ruby',750,'ml','Bottle'),
  ('cockburns-special-reserve',1,'L','Bottle'),
  ('cockburns-special-reserve',750,'ml','Bottle'),
  ('courvoisier-vsop-tripple-oak',1,'L','Bottle'),
  ('courvoisier-vsop-tripple-oak',700,'ml','Bottle'),
  ('culemborg-cape-red',750,'ml','Bottle'),
  ('cutty-sark',750,'ml','Bottle'),
  ('dalwhinnie-15-years',1,'L','Bottle'),
  ('dalwhinnie-15-years',750,'ml','Bottle'),
  ('dead-mans-finger-coffee-rum',750,'ml','Bottle'),
  ('dead-mans-fingers-coconut-rum',750,'ml','Bottle'),
  ('don-montego',500,'ml','Bottle'),
  ('drostdy-hof-premier-grand-cru-white-dry',750,'ml','Bottle'),
  ('drostdy-hof-white-sweet',750,'ml','Bottle'),
  ('early-times-kentucky-straight-bourbon-whisky',750,'ml','Bottle'),
  ('el-charro-gold',750,'ml','Bottle'),
  ('el-charro-silver',750,'ml','Bottle'),
  ('el-jimador-blanco',750,'ml','Bottle'),
  ('el-jimador-reposado',1,'L','Bottle'),
  ('el-jimador-reposado',750,'ml','Bottle'),
  ('elephant-handcrafted-london-dry-gin',500,'ml','Bottle'),
  ('elephant-handcrafted-london-dry-gin',700,'ml','Bottle'),
  ('finlandia-blackcurrant',1,'L','Bottle'),
  ('finlandia-blackcurrant',750,'ml','Bottle'),
  ('finlandia-grapefruit',1,'L','Bottle'),
  ('finlandia-grapefruit',750,'ml','Bottle'),
  ('finlandia-vodka-original',1,'L','Bottle'),
  ('finlandia-vodka-original',750,'ml','Bottle'),
  ('firewater-cinnamon',1,'L','Bottle'),
  ('firewater-cinnamon',750,'ml','Bottle'),
  ('flirt-vodka-golden-apple',1,'L','Bottle'),
  ('flirt-vodka-golden-apple',1.5,'L','Bottle'),
  ('flirt-vodka-golden-apple',750,'ml','Bottle'),
  ('flirt-vodka-orange',1,'L','Bottle'),
  ('flirt-vodka-orange',1.5,'L','Bottle'),
  ('flirt-vodka-orange',750,'ml','Bottle'),
  ('four-cousins-chardonnay',750,'ml','Bottle'),
  ('fragolino-bianco-morando',750,'ml','Bottle'),
  ('frontera-caberbet-sauvignon',1.5,'L','Bottle'),
  ('frontera-caberbet-sauvignon',750,'ml','Bottle'),
  ('frontera-chardonnay',1.5,'L','Bottle'),
  ('frontera-chardonnay',750,'ml','Bottle'),
  ('frontera-merlot',1.5,'L','Bottle'),
  ('frontera-merlot',750,'ml','Bottle'),
  ('frontera-pinot-grigio',750,'ml','Bottle'),
  ('frontera-sauvignon-blanc',1,'L','Bottle'),
  ('frontera-sauvignon-blanc',750,'ml','Bottle'),
  ('frontera-shiraz',1.5,'L','Bottle'),
  ('frontera-shiraz',750,'ml','Bottle'),
  ('frontera-sparkling-moscato',750,'ml','Bottle'),
  ('frontera-sparkling-rose',750,'ml','Bottle'),
  ('frontera-sweet-red',750,'ml','Bottle'),
  ('fundador-solera-reserva',1,'L','Bottle'),
  ('gato-negro-cabernet-merlot',1.5,'L','Bottle'),
  ('gato-negro-cabernet-merlot',750,'ml','Bottle'),
  ('gato-negro-cabernet-sauvignon',1.5,'L','Bottle'),
  ('gato-negro-cabernet-sauvignon',750,'ml','Bottle'),
  ('gato-negro-chardonnay',1.5,'L','Bottle'),
  ('gato-negro-chardonnay',750,'ml','Bottle'),
  ('gato-negro-merlot',1.5,'L','Bottle'),
  ('gato-negro-merlot',750,'ml','Bottle'),
  ('gato-negro-sauvignon-blanc',1.5,'L','Bottle'),
  ('gato-negro-sauvignon-blanc',750,'ml','Bottle'),
  ('gato-negro-shiraz',1.5,'L','Bottle'),
  ('gato-negro-shiraz',750,'ml','Bottle'),
  ('gibsons-pink-premium-gin',750,'ml','Bottle'),
  ('glen-silvers',1,'L','Bottle'),
  ('glen-silvers',750,'ml','Bottle'),
  ('glenlivet-12',1,'L','Bottle'),
  ('glenlivet-12',750,'ml','Bottle'),
  ('glenlivet-12-years-double-oak',1,'L','Bottle'),
  ('glenlivet-12-years-double-oak',750,'ml','Bottle'),
  ('gordons-pink-gin',1,'L','Bottle'),
  ('gordons-pink-gin',750,'ml','Bottle'),
  ('grants-signature',750,'ml','Bottle'),
  ('h-by-hine-vsop',1,'L','Bottle'),
  ('h-by-hine-vsop',700,'ml','Bottle'),
  ('harveys-bristol-cream-sherry',1,'L','Bottle'),
  ('harveys-bristol-cream-sherry',750,'ml','Bottle'),
  ('heineken-original',6,'piece','Six-pack bottles'),
  ('heineken-original',6,'piece','Six-pack cans'),
  ('heineken-zero',6,'piece','Six pack'),
  ('hennessy-masters-blend',500,'ml','Bottle'),
  ('hine-rare',1,'L','Bottle'),
  ('hine-rare',700,'ml','Bottle'),
  ('hunters-gold',6,'piece','Six pack'),
  ('j-and-b-honey',750,'ml','Bottle'),
  ('j-and-b-rare',1,'L','Bottle'),
  ('j-and-b-rare',750,'ml','Bottle'),
  ('jack-daniels-apple',1,'L','Bottle'),
  ('jack-daniels-apple',750,'ml','Bottle'),
  ('jack-daniels-honey',1,'L','Bottle'),
  ('jack-daniels-honey',750,'ml','Bottle'),
  ('jack-daniels-tennessee-cola',330,'ml','Bottle'),
  ('jack-daniels-tennessee-fire',1,'L','Bottle'),
  ('jack-daniels-tennessee-fire',750,'ml','Bottle'),
  ('jack-daniels-tennessee-fire-liqueur',1,'L','Bottle'),
  ('jack-daniels-tennessee-fire-liqueur',750,'ml','Bottle'),
  ('jack-daniels-tennessee-rye',1,'L','Bottle'),
  ('jack-daniels-tennessee-rye',750,'ml','Bottle'),
  ('jagermeister',1,'L','Bottle'),
  ('jagermeister',750,'ml','Bottle'),
  ('jim-beam',750,'ml','Bottle'),
  ('jim-beam-apple',1,'L','Bottle'),
  ('jim-beam-apple',750,'ml','Bottle'),
  ('jim-beam-apple-liqueur',1,'L','Bottle'),
  ('jim-beam-apple-liqueur',750,'ml','Bottle'),
  ('jim-beam-honey-liqueur',1,'L','Bottle'),
  ('jim-beam-honey-liqueur',750,'ml','Bottle'),
  ('jim-beam-red-stag',1,'L','Bottle'),
  ('jim-beam-red-stag',750,'ml','Bottle'),
  ('jim-beam-red-stag-liqueur',1,'L','Bottle'),
  ('jim-beam-red-stag-liqueur',750,'ml','Bottle'),
  ('jim-beam-signature-craft',1,'L','Bottle'),
  ('jim-beam-signature-craft',750,'ml','Bottle'),
  ('john-bannermans',750,'ml','Bottle'),
  ('john-barr',750,'ml','Bottle'),
  ('jose-cuervo-especial-gold',1,'L','Bottle'),
  ('jose-cuervo-especial-gold',750,'ml','Bottle'),
  ('jose-cuervo-especial-silver',1,'L','Bottle'),
  ('jose-cuervo-especial-silver',750,'ml','Bottle'),
  ('jp-chenet-apple',750,'ml','Bottle'),
  ('jp-chenet-pineapple',750,'ml','Bottle'),
  ('jp-chenet-strawberry-and-raspberry',750,'ml','Bottle'),
  ('jura-16',1,'L','Bottle'),
  ('jura-16',750,'ml','Bottle'),
  ('jura-16-years',1,'L','Bottle'),
  ('jura-16-years',750,'ml','Bottle'),
  ('karibrew-craft-beer',6,'piece','Six pack'),
  ('kensington',750,'ml','Bottle'),
  ('kenyan-originals-craft-cider',6,'piece','Six pack'),
  ('kwv-3-years',750,'ml','Bottle'),
  ('kwv-cruxland-black-winter-gin',1,'L','Bottle'),
  ('kwv-cruxland-black-winter-gin',750,'ml','Bottle'),
  ('lambrusco-dellemilia-amabile-bianco',750,'ml','Bottle'),
  ('larios-12',700,'ml','Bottle'),
  ('larios-dry-gin',1,'L','Bottle'),
  ('larios-rose',700,'ml','Bottle'),
  ('lauders-blended-scotch-whisky',700,'ml','Bottle'),
  ('leffe',330,'ml','Bottle'),
  ('leleshwa-rose',750,'ml','Bottle'),
  ('leleshwa-sauvignon-blanc',750,'ml','Bottle'),
  ('leleshwa-white-dry',750,'ml','Bottle'),
  ('limoncello-caducale',1,'L','Bottle'),
  ('limoncello-caducale',2,'L','Bottle'),
  ('limoncello-di-capri',1,'L','Bottle'),
  ('limoncello-di-capri',750,'ml','Bottle'),
  ('lombard-gold-label',1,'L','Bottle'),
  ('los-cabos-gold',750,'ml','Bottle'),
  ('los-cabos-silver',750,'ml','Bottle'),
  ('malfy-con-arancia',1,'L','Bottle'),
  ('malfy-con-arancia',750,'ml','Bottle'),
  ('malfy-con-gin-rosa',1,'L','Bottle'),
  ('malfy-con-gin-rosa',750,'ml','Bottle'),
  ('malfy-con-limone',1,'L','Bottle'),
  ('malfy-con-limone',750,'ml','Bottle'),
  ('malibu-black',1,'L','Bottle'),
  ('malibu-black',750,'ml','Bottle'),
  ('mamma-mia-red-sweet',750,'ml','Bottle'),
  ('manyatta-beer',6,'piece','Six pack'),
  ('mara-nyekundu',1.5,'L','Bottle'),
  ('mara-nyekundu',750,'ml','Bottle'),
  ('mara-nyeupe',1.5,'L','Bottle'),
  ('mara-nyeupe',750,'ml','Bottle'),
  ('marshalls-bourbon-whiskey',700,'ml','Bottle'),
  ('martini-extra-dry',1,'L','Bottle'),
  ('martini-extra-dry',750,'ml','Bottle'),
  ('meukow-vs',1,'L','Bottle'),
  ('meukow-vs',750,'ml','Bottle'),
  ('monkey-shoulder',1,'L','Bottle'),
  ('monkey-shoulder',750,'ml','Bottle'),
  ('myers-rum',1,'L','Bottle'),
  ('myers-rum',750,'ml','Bottle'),
  ('namaqua-pinotage',750,'ml','Bottle'),
  ('namaqua-rose',750,'ml','Bottle'),
  ('namaqua-sweet-white',750,'ml','Bottle'),
  ('negrita-bardinet-rum',750,'ml','Bottle'),
  ('new-grove-silver',750,'ml','Bottle'),
  ('new-grove-spiced-rum',750,'ml','Bottle'),
  ('oak-wooded-unit-43-gin',750,'ml','Bottle'),
  ('obikwa-cabernet-sauvignon-2016',750,'ml','Bottle'),
  ('obikwa-pinotage',750,'ml','Bottle'),
  ('odriscoll-irish-whiskey',750,'ml','Bottle'),
  ('oj-8-5',6,'piece','Six pack'),
  ('old-nick-golden-rum',750,'ml','Bottle'),
  ('old-nick-white-rum',750,'ml','Bottle'),
  ('old-smuggler',750,'ml','Bottle'),
  ('paddy-irish-whiskey',1,'L','Bottle'),
  ('paddy-irish-whiskey',750,'ml','Bottle'),
  ('passport-scotch',750,'ml','Bottle'),
  ('penasol-sangria',1,'L','Bottle'),
  ('penasol-sangria',1.5,'L','Bottle'),
  ('porto-cruz-tawny',1,'L','Bottle'),
  ('porto-cruz-tawny',750,'ml','Bottle'),
  ('puianello-primabolla-reggiano-doc-lambrusco',750,'ml','Bottle'),
  ('remy-martin-club-cognac',1,'L','Bottle'),
  ('remy-martin-club-cognac',700,'ml','Bottle'),
  ('rendez-vous-pink',750,'ml','Bottle'),
  ('rendez-vous-red-grape',750,'ml','Bottle'),
  ('rendez-vous-sparkling-apple',750,'ml','Bottle'),
  ('rendez-vous-sparkling-blue',750,'ml','Bottle'),
  ('rendez-vous-sparkling-white-grape',750,'ml','Bottle'),
  ('richot',750,'ml','Bottle'),
  ('saint-celine-sweet-red',750,'ml','Bottle'),
  ('sandtrap-ipa-craft-beer',6,'piece','Six pack'),
  ('santa-helena-dulce',750,'ml','Bottle'),
  ('sauza-tequila-silver',1,'L','Bottle'),
  ('sauza-tequila-silver',750,'ml','Bottle'),
  ('scots-gold-black',1,'L','Bottle'),
  ('scots-gold-black',750,'ml','Bottle'),
  ('scottish-leader-original-whisky',750,'ml','Bottle'),
  ('sikera-apple-cider',6,'piece','Six pack'),
  ('skyy-blood-orange',1,'L','Bottle'),
  ('skyy-blood-orange',750,'ml','Bottle'),
  ('skyy-cherry',1,'L','Bottle'),
  ('skyy-cherry',750,'ml','Bottle'),
  ('skyy-coconut',1,'L','Bottle'),
  ('skyy-coconut',750,'ml','Bottle'),
  ('skyy-dragon-fruit',1,'L','Bottle'),
  ('skyy-dragon-fruit',750,'ml','Bottle'),
  ('skyy-ginger',1,'L','Bottle'),
  ('skyy-ginger',750,'ml','Bottle'),
  ('skyy-grape',1,'L','Bottle'),
  ('skyy-grape',750,'ml','Bottle'),
  ('skyy-passion',1,'L','Bottle'),
  ('skyy-passion',750,'ml','Bottle'),
  ('skyy-raspberry',1,'L','Bottle'),
  ('skyy-raspberry',750,'ml','Bottle'),
  ('skyy-vodka',1,'L','Bottle'),
  ('skyy-vodka',750,'ml','Bottle'),
  ('smirnoff-citrus',1,'L','Bottle'),
  ('smirnoff-citrus',750,'ml','Bottle'),
  ('smirnoff-espresso',1,'L','Bottle'),
  ('smirnoff-espresso',750,'ml','Bottle'),
  ('smirnoff-green-apple',1,'L','Bottle'),
  ('smirnoff-green-apple',750,'ml','Bottle'),
  ('smirnoff-ice-double-black-with-guarana',6,'piece','Six pack'),
  ('smirnoff-raspberry',1,'L','Bottle'),
  ('smirnoff-raspberry',750,'ml','Bottle'),
  ('snapp',6,'piece','Six-pack cans'),
  ('sunkissed-natural-sweet-white-wine',750,'ml','Bottle'),
  ('tanqueray-flor-de-sevilla-distilled-gin',1,'L','Bottle'),
  ('tanqueray-flor-de-sevilla-distilled-gin',750,'ml','Bottle'),
  ('teeling-whiskey-small-batch',1,'L','Bottle'),
  ('teeling-whiskey-small-batch',750,'ml','Bottle'),
  ('tequila-sauza-gold',1,'L','Bottle'),
  ('tequila-sauza-gold',750,'ml','Bottle'),
  ('the-famous-grouse-smoky-black',750,'ml','Bottle'),
  ('the-kraken-black-spiced-rum',1,'L','Bottle'),
  ('the-kraken-black-spiced-rum',750,'ml','Bottle'),
  ('the-snow-grouse',750,'ml','Bottle'),
  ('tijuana-sweet-heat',750,'ml','Bottle'),
  ('tio-pepe-sherry',1,'L','Bottle'),
  ('tio-pepe-sherry',750,'ml','Bottle'),
  ('tuborg',6,'piece','Six pack'),
  ('tullamore-dew-xo-caribbean-rum-finish',1,'L','Bottle'),
  ('tullamore-dew-xo-caribbean-rum-finish',750,'ml','Bottle'),
  ('upper-valley-nabygelegen-dry-red',1.5,'L','Bottle'),
  ('upper-valley-nabygelegen-dry-red',750,'ml','Bottle'),
  ('upper-valley-nabygelegen-sweet-red',1.5,'L','Bottle'),
  ('upper-valley-nabygelegen-sweet-red',750,'ml','Bottle'),
  ('upper-valley-nabygelegen-sweet-white',1.5,'L','Bottle'),
  ('upper-valley-nabygelegen-sweet-white',750,'ml','Bottle'),
  ('upper-valley-nabygelegen-white-dry',1.5,'L','Bottle'),
  ('upper-valley-nabygelegen-white-dry',750,'ml','Bottle'),
  ('versus-red-dry',750,'ml','Bottle'),
  ('versus-sweet-red',750,'ml','Bottle'),
  ('whitley-neil-quince-handcrafted-dry-gin',1,'L','Bottle'),
  ('whitley-neil-quince-handcrafted-dry-gin',750,'ml','Bottle'),
  ('whitley-neill-gooseberry-gin',1,'L','Bottle'),
  ('whitley-neill-gooseberry-gin',750,'ml','Bottle'),
  ('whitley-neill-handcrafted-aloe-and-cucumber-gin',1,'L','Bottle'),
  ('whitley-neill-handcrafted-aloe-and-cucumber-gin',750,'ml','Bottle'),
  ('whitley-neill-handcrafted-blood-orange-gin',1,'L','Bottle'),
  ('whitley-neill-handcrafted-blood-orange-gin',750,'ml','Bottle'),
  ('whitley-neill-handcrafted-lemongrass-and-ginger-gin',1,'L','Bottle'),
  ('whitley-neill-handcrafted-lemongrass-and-ginger-gin',750,'ml','Bottle'),
  ('whitley-neill-handcrafted-parma-violet-gin',1,'L','Bottle'),
  ('whitley-neill-handcrafted-parma-violet-gin',750,'ml','Bottle'),
  ('whitley-neill-handcrafted-raspberry-gin',1,'L','Bottle'),
  ('whitley-neill-handcrafted-raspberry-gin',750,'ml','Bottle'),
  ('whitley-neill-original-gin',1,'L','Bottle'),
  ('whitley-neill-original-gin',700,'ml','Bottle'),
  ('whitley-neill-original-handcrafted-dry-gin',1,'L','Bottle'),
  ('whitley-neill-original-handcrafted-dry-gin',750,'ml','Bottle'),
  ('whitley-neill-rhubarb-and-ginger-gin',1,'L','Bottle'),
  ('whitley-neill-rhubarb-and-ginger-gin',750,'ml','Bottle'),
  ('whyte-and-mackay',750,'ml','Bottle'),
  ('woodford-reserve',1,'L','Bottle'),
  ('woodford-reserve',700,'ml','Bottle')
)
insert into public.catalog_product_variants (
  catalog_product_id,
  volume_value,
  volume_unit,
  package_type
)
select cp.id, vd.volume_value, vd.volume_unit, vd.package_type
from variant_data vd
join public.catalog_products cp on cp.slug = vd.slug
on conflict (catalog_product_id, volume_value, volume_unit, package_type)
do update set active = true, updated_at = now();
